// A2DiffTest — byte-equal regression gate for the AST-based codegen path.
//
// Runs the IR pipeline (MASTPipeline::Run + CodeGenerator IR entry points) to
// /tmp/a2_ir and diffs every shared filename against the legacy string-parser
// output that already lives in Build/Generated/. Files only one path emits are
// reported but do not fail the test — that's A3 / follow-up work (MObject /
// Properties / TypeAliases / bInjection / Metadata IR fields are still empty
// in the current AST visitor, so IR-side emits are intentionally incomplete).
//
// Files BOTH paths emit must be byte-equal after timestamp-strip. That is the
// regression gate for the A2 codegen migration.

#include "AST/ASTPipeline.h"
#include "Core/Types.h"
#include "Generation/CodeGenerator.h"
#include "Util/FileUtil.h"
#include "Common/Runtime/Log/Tests/TestHarness.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;
namespace mession::headercodegen {

    // Read a file's full contents into a string.
    static MString ReadFile(const fs::path& Path) {
        std::ifstream F(Path);
        if (!F) {
            return {};
        }
        std::stringstream SS;
        SS << F.rdbuf();
        return SS.str();
    }

    // Strip the "// Generated by MHeaderTool ... <timestamp>" line so two
    // runs at different times can still be compared. Today the line has no
    // timestamp payload (it's a literal `// Generated by MHeaderTool\n`), so
    // the strip is effectively a no-op when neither side carries one; if a
    // timestamp ever gets injected (e.g. for incremental builds), this will
    // continue to do the right thing without rewriting the test.
    static void StripTimestamp(MString& InOut) {
        const MString Marker = "// Generated by MHeaderTool";
        const size_t  Pos    = InOut.find(Marker);
        if (Pos == MString::npos) {
            return;
        }
        const size_t End = InOut.find('\n', Pos);
        if (End == MString::npos) {
            return;
        }
        InOut.erase(Pos, End - Pos);
    }

    TEST_CASE(A2DiffTest_FullHeaderIR) {
        // --- 1. Drive the IR pipeline into /tmp/a2_ir ----------------------------
        MHeaderTool::SOptions Options;
        Options.SourceRoot = "Source";

        const fs::path IRDir = "/tmp/a2_ir";

        std::error_code Ec;
        fs::remove_all(IRDir, Ec);
        fs::create_directories(IRDir, Ec);

        Options.OutputDir = IRDir;
        SParseIR IR       = MASTPipeline::Run(Options);

        std::printf("A2DiffTest: IR pipeline produced %zu records\n", IR.Records.size());

        MHeaderTool::CodeGenerator CodeGen(Options);
        for (const SParsedRecord& Record : IR.Records) {
            const MString HeaderCode = CodeGen.GenerateHeaderFromIR(Record, IR.Records);
            MHeaderTool::WriteFile(IRDir / (MHeaderTool::SanitizeIdentifier(Record.Name) + ".mgenerated.h"), HeaderCode);
        }

        // --- 2. Bucket IR-side filenames -----------------------------------------
        TVector<MString> IRSide;
        for (const auto& Entry : fs::directory_iterator(IRDir)) {
            if (!Entry.is_regular_file()) {
                continue;
            }
            IRSide.push_back(Entry.path().filename().string());
        }

        // --- 3. Bucket legacy-side filenames -------------------------------------
        const fs::path   LegacyDir = "Build/Generated";
        TVector<MString> LegacySide;
        if (fs::exists(LegacyDir)) {
            for (const auto& Entry : fs::directory_iterator(LegacyDir)) {
                if (!Entry.is_regular_file()) {
                    continue;
                }
                LegacySide.push_back(Entry.path().filename().string());
            }
        }

        // --- 4. Compute set intersections ----------------------------------------
        auto Contains = [](const TVector<MString>& V, const MString& Name) -> bool {
            for (const MString& S : V) {
                if (S == Name) {
                    return true;
                }
            }
            return false;
        };

        int NumShared     = 0;
        int NumIdentical  = 0;
        int NumDivergent  = 0;
        int NumIROnly     = 0;
        int NumLegacyOnly = 0;

        std::printf("\n=== A2DiffTest per-file comparison (after StripTimestamp) ===\n");
        std::printf("%-50s  %-9s  %s\n", "Filename", "Status", "Notes");
        std::printf("%-50s  %-9s  %s\n", "----------------------------------------", "---------", "----------------------------------------");

        // Shared files: compare both directions so a file present on both sides
        // gets a single row, not two.
        for (const MString& Name : IRSide) {
            if (!Contains(LegacySide, Name)) {
                ++NumIROnly;
                std::printf("%-50s  %-9s  %s\n", Name.c_str(), "IR_ONLY", "emitted by AST path; not in legacy Build/Generated — A3 work");
                continue;
            }

            ++NumShared;

            MString IRText     = ReadFile(IRDir / Name);
            MString StrippedIR = IRText;
            StripTimestamp(StrippedIR);

            MString LegacyText     = ReadFile(LegacyDir / Name);
            MString StrippedLegacy = LegacyText;
            StripTimestamp(StrippedLegacy);

            const bool bEqual = (StrippedIR == StrippedLegacy);
            if (bEqual) {
                ++NumIdentical;
                std::printf("%-50s  %-9s  %s\n", Name.c_str(), "EQUAL", "");
            } else {
                ++NumDivergent;
                std::printf("%-50s  %-9s  %s\n", Name.c_str(), "DIVERGE", "see report; AST path diverges from legacy byte-content");
            }

            // EXPECT_TRUE for shared files is the regression gate. Divergences
            // accumulate as failures so RUN_TESTS reports aggregate counts;
            // the report file (per the brief) characterizes each divergence.
            EXPECT_TRUE(bEqual);
        }

        // Legacy-only files: present in Build/Generated but not emitted by the
        // AST path. Report them but do not fail — that's A3 / follow-up scope
        // (MObject / Properties / TypeAliases / bInjection / Metadata IR fields
        // are still empty, so the AST visitor can't see these types yet).
        for (const MString& Name : LegacySide) {
            if (Contains(IRSide, Name)) {
                continue;
            }
            ++NumLegacyOnly;
            std::printf("%-50s  %-9s  %s\n", Name.c_str(), "LEGACY_ONLY", "in legacy Build/Generated; not emitted by AST path yet");
        }

        std::printf("\n=== A2DiffTest summary ===\n");
        std::printf("  shared files   : %d\n", NumShared);
        std::printf("    identical    : %d\n", NumIdentical);
        std::printf("    divergent    : %d\n", NumDivergent);
        std::printf("  IR-only files  : %d\n", NumIROnly);
        std::printf("  legacy-only    : %d\n", NumLegacyOnly);
        std::printf("\nShared-file divergences are the regression gate. Legacy-only\n");
        std::printf("files are not gates — they exist because the AST visitor does not\n");
        std::printf("yet populate Properties / TypeAliases / bInjection / Metadata, and\n");
        std::printf("MCLASS / MGENERATED_BODY filtering for MObject is incomplete. That's\n");
        std::printf("A3 / follow-up work; Task 9 is the measurement, A3 is the fix.\n");
    }

} // namespace mession::headercodegen

int main() {
    std::printf("Running A2DiffTest\n");
    mession::headercodegen::Test_A2DiffTest_FullHeaderIR();
    RUN_TESTS();
    return 0;
}
