// A2DiffTest — byte-equal regression gate for the AST-based codegen path.
//
// Runs the IR pipeline (MASTPipeline::Run + MCodeGenerator IR entry points) to
// /tmp/a2_ir and diffs every shared filename against the immutable legacy
// baseline at /tmp/legacy_baseline/ (a one-time copy of
// /root/Mession/Build/Generated/ taken BEFORE the AST path was introduced —
// see commit d0785c8, the AST path that overwrote Build/Generated with AST
// output). Files only one path emits are reported but do not fail the test —
// that's A3 / follow-up work.
//
// Files BOTH paths emit must be byte-equal after timestamp-strip. That is the
// regression gate for the A2 codegen migration.

#include "AST/ASTPipeline.h"
#include "Core/Types.h"
#include "Generation/CodeGenerator.h"
#include "Util/FileUtil.h"
#include "Common/Runtime/Log/Tests/TestHarness.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;
namespace mession::headercodegen {

    // Read a file's full contents into a string.
    static MString ReadFile(const fs::path& Path) {
        std::ifstream F(Path);
        if (!F) {
            return {};
        }
        std::stringstream SS;
        SS << F.rdbuf();
        return SS.str();
    }

    // Strip the "// Generated by MHeaderTool ... <timestamp>" line so two
    // runs at different times can still be compared. Today the line has no
    // timestamp payload (it's a literal `// Generated by MHeaderTool\n`), so
    // the strip is effectively a no-op when neither side carries one; if a
    // timestamp ever gets injected (e.g. for incremental builds), this will
    // continue to do the right thing without rewriting the test.
    static void StripTimestamp(MString& InOut) {
        const MString Marker = "// Generated by MHeaderTool";
        const size_t  Pos    = InOut.find(Marker);
        if (Pos == MString::npos) {
            return;
        }
        const size_t End = InOut.find('\n', Pos);
        if (End == MString::npos) {
            return;
        }
        InOut.erase(Pos, End - Pos);
    }

    TEST_CASE(A2DiffTest_FullHeaderIR) {
        // --- 1. Drive the IR pipeline into /tmp/a2_ir ----------------------------
        MHeaderTool::SOptions Options;
        Options.SourceRoot = "Source";

        const fs::path IRDir = "/tmp/a2_ir";

        std::error_code Ec;
        fs::remove_all(IRDir, Ec);
        fs::create_directories(IRDir, Ec);

        Options.OutputDir = IRDir;
        SParseIR IR       = MASTPipeline::Run(Options);

        std::printf("A2DiffTest: IR pipeline produced %zu records\n", IR.Records.size());

        MHeaderTool::MCodeGenerator CodeGen(Options);
        for (const SParsedRecord& Record : IR.Records) {
            const MString HeaderCode = CodeGen.GenerateHeaderFromIR(Record, IR.Records);
            MHeaderTool::WriteFile(IRDir / (MHeaderTool::SanitizeIdentifier(Record.Name) + ".mgenerated.h"), HeaderCode);
        }

        // --- 2. Bucket IR-side filenames -----------------------------------------
        TVector<MString> IRSide;
        for (const auto& Entry : fs::directory_iterator(IRDir)) {
            if (!Entry.is_regular_file()) {
                continue;
            }
            IRSide.push_back(Entry.path().filename().string());
        }

        // --- 3. Bucket legacy-side filenames -------------------------------------
        // /tmp/legacy_baseline/ is a one-time copy of the pre-AST
        // /root/Mession/Build/Generated/ (commit d0785c8 overwrote
        // Build/Generated with AST output, so Build/Generated/ is no longer a
        // valid legacy baseline). The test prints a warning if the baseline
        // is missing so a fresh checkout doesn't silently compare against an
        // empty directory.
        const fs::path LegacyDir = "/tmp/legacy_baseline";
        if (!fs::exists(LegacyDir)) {
            std::printf("A2DiffTest: WARNING legacy baseline %s does not exist; "
                        "run `cp -r /root/Mession/Build/Generated/ /tmp/legacy_baseline/` "
                        "first to establish the pre-AST reference.\n",
                        LegacyDir.c_str());
        }
        TVector<MString> LegacySide;
        if (fs::exists(LegacyDir)) {
            for (const auto& Entry : fs::directory_iterator(LegacyDir)) {
                if (!Entry.is_regular_file()) {
                    continue;
                }
                LegacySide.push_back(Entry.path().filename().string());
            }
        }

        // --- 4. Compute set intersections ----------------------------------------
        auto Contains = [](const TVector<MString>& V, const MString& Name) -> bool {
            for (const MString& S : V) {
                if (S == Name) {
                    return true;
                }
            }
            return false;
        };

        int NumSharedEql  = 0;
        int NumSharedNeq  = 0;
        int NumIROnly     = 0;
        int NumLegacyOnly = 0;

        std::printf("\n=== A2DiffTest per-file comparison (after StripTimestamp) ===\n");
        std::printf("%-50s  %-20s  %s\n", "Filename", "Status", "First divergence / note");
        std::printf("%-50s  %-20s  %s\n", "----------------------------------------", "--------------------", "----------------------------------------");

        // 找到 IR-side / legacy-side 文件名第一个出现差异的行号（返回 MString::npos 时等同完全相等）。
        auto FirstDivergence = [](const MString& A, const MString& B) -> size_t {
            const size_t Limit = std::min(A.size(), B.size());
            for (size_t i = 0; i < Limit; ++i) {
                if (A[i] != B[i])
                    return i;
            }
            return MString::npos;
        };

        // Shared files: compare both directions so a file present on both sides
        // gets a single row, not two.
        for (const MString& Name : IRSide) {
            if (!Contains(LegacySide, Name)) {
                ++NumIROnly;
                std::printf("%-50s  %-20s  %s\n", Name.c_str(), "AST_ONLY", "emitted by AST path; not in legacy baseline — A3 work");
                continue;
            }

            MString IRText     = ReadFile(IRDir / Name);
            MString StrippedIR = IRText;
            StripTimestamp(StrippedIR);

            MString LegacyText     = ReadFile(LegacyDir / Name);
            MString StrippedLegacy = LegacyText;
            StripTimestamp(StrippedLegacy);

            const bool bEqual = (StrippedIR == StrippedLegacy);
            if (bEqual) {
                ++NumSharedEql;
                std::printf("%-50s  %-20s  %s\n", Name.c_str(), "AST_EQL_LEGACY", "");
            } else {
                ++NumSharedNeq;
                const size_t DivPos = FirstDivergence(StrippedIR, StrippedLegacy);
                MString      Note =
                    (DivPos == MString::npos) ? MString("length differs (ir=") + std::to_string(StrippedIR.size()) + ", legacy=" + std::to_string(StrippedLegacy.size()) + ")" : MString("first diff at byte ") + std::to_string(DivPos);
                std::printf("%-50s  %-20s  %s\n", Name.c_str(), "AST_NEQ_LEGACY", Note.c_str());
            }

            // EXPECT_TRUE for shared files is the regression gate. Divergences
            // accumulate as failures so RUN_TESTS reports aggregate counts;
            // the report file (per the brief) characterizes each divergence.
            EXPECT_TRUE(bEqual);
        }

        // Legacy-only files: present in legacy baseline but not emitted by the
        // AST path. Report them but do not fail — that's A3 / follow-up scope.
        for (const MString& Name : LegacySide) {
            if (Contains(IRSide, Name)) {
                continue;
            }
            ++NumLegacyOnly;
            std::printf("%-50s  %-20s  %s\n", Name.c_str(), "LEGACY_ONLY", "in legacy baseline; not emitted by AST path yet");
        }

        std::printf("\n=== A2DiffTest summary ===\n");
        std::printf("  AST_EQL_LEGACY : %d\n", NumSharedEql);
        std::printf("  AST_NEQ_LEGACY : %d\n", NumSharedNeq);
        std::printf("  AST_ONLY       : %d\n", NumIROnly);
        std::printf("  LEGACY_ONLY    : %d\n", NumLegacyOnly);
        std::printf("\nAST_NEQ_LEGACY files are the regression gate. LEGACY_ONLY / AST_ONLY\n");
        std::printf("files are not gates — they exist because the AST visitor does not\n");
        std::printf("yet populate every IR field, and MCLASS / MGENERATED_BODY filtering\n");
        std::printf("for some types is incomplete. That's A3 / follow-up work; Task 9 is\n");
        std::printf("the measurement, A3 is the fix.\n");
    }

} // namespace mession::headercodegen

int main() {
    std::printf("Running A2DiffTest\n");
    mession::headercodegen::Test_A2DiffTest_FullHeaderIR();
    RUN_TESTS();
    return 0;
}
