#pragma once

#include "Core/Types.h"
#include "Util/StringUtil.h"
#include <filesystem>
#include <sstream>
#include <regex>

namespace fs = std::filesystem;

namespace MHeaderTool
{

// ============================================================================
// Code Generator - 生成兼容原始格式的代码
// ============================================================================

class CodeGenerator
{
public:
    explicit CodeGenerator(const SOptions& options)
        : Options_(options)
    {
    }

    // 生成头文件内容
    std::string GenerateHeader(const SParsedClass& parsedClass) const
    {
        std::ostringstream out;

        out << "#pragma once\n";
        out << "// Generated by MHeaderTool\n";
        out << "// Source: " << parsedClass.HeaderPath.string() << "\n";
        out << "// Reflected " << GetTypeKindName(parsedClass.Kind) << ": " << parsedClass.Name << "\n";
        out << "\n";

        // 包含必要的头文件
        out << "#include \"Common/Net/Rpc/RpcClientCall.h\"\n";
        out << "#include \"Common/Net/Rpc/RpcServerCall.h\"\n";
        out << "#include \"Common/Runtime/Async/MAsync.h\"\n";
        out << "#include \"Servers/App/ServerCallRequestValidation.h\"\n";
        out << "#include \"Protocol/Messages/World/PlayerModifyMessages.h\"\n";
        out << "#include \"Protocol/Messages/World/PlayerQueryMessages.h\"\n";
        out << "#include \"Protocol/Messages/World/PlayerRouteMessages.h\"\n";
        out << "#include \"Protocol/Messages/World/PlayerSocialMessages.h\"\n";
        out << "#include \"Protocol/Messages/World/PlayerLifecycleMessages.h\"\n";
        out << "#include \"Protocol/Messages/Scene/SceneServiceMessages.h\"\n";
        out << "#include \"Protocol/Messages/Combat/CombatWorldMessages.h\"\n";
        out << "\n";

        if (parsedClass.Kind == EParsedTypeKind::Enum)
        {
            GenerateEnumHeader(out, parsedClass);
        }
        else if (parsedClass.Kind == EParsedTypeKind::Struct)
        {
            GenerateStructHeader(out, parsedClass);
        }
        else
        {
            GenerateClassHeader(out, parsedClass);
        }

        return out.str();
    }

    // 生成源文件内容
    std::string GenerateSource(const SParsedClass& parsedClass) const
    {
        std::ostringstream out;

        std::string includeName = MakeIncludePathFromHeader(parsedClass.HeaderPath);
        std::string generatedHeader = SanitizeIdentifier(parsedClass.Name) + ".mgenerated.h";

        out << "// Generated by MHeaderTool\n";
        out << "// Source: " << parsedClass.HeaderPath.string() << "\n";
        out << "#include \"" << includeName << "\"\n";
        out << "#include \"" << generatedHeader << "\"\n";
        out << "\n\n";

        if (parsedClass.Kind == EParsedTypeKind::Enum)
        {
            GenerateEnumSource(out, parsedClass);
        }
        else if (parsedClass.Kind == EParsedTypeKind::Struct)
        {
            GenerateStructSource(out, parsedClass);
        }
        else
        {
            GenerateClassSource(out, parsedClass);
        }

        return out.str();
    }

private:
    void GenerateEnumHeader(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "inline MEnum* MHeaderTool_Generated_RegisterEnum_" << parsedClass.Name << "()\n";
        out << "{\n";
        out << "    static MEnum* Enum = nullptr;\n";
        out << "    if (!Enum)\n";
        out << "    {\n";
        out << "        Enum = new MEnum(\"" << parsedClass.Name << "\", \"" << parsedClass.HeaderPath.generic_string() << "\", std::type_index(typeid(" << parsedClass.Name << ")));\n";
        for (const std::string& value : parsedClass.EnumValues)
        {
            std::string qualifiedValue = parsedClass.bScopedEnum
                ? (parsedClass.Name + "::" + value)
                : value;
            out << "        Enum->AddValue(\"" << value << "\", static_cast<int64>(" << qualifiedValue << "));\n";
        }
        out << "        MObject::RegisterEnum(Enum);\n";
        out << "    }\n";
        out << "    return Enum;\n";
        out << "}\n";
    }

    void GenerateEnumSource(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "namespace\n";
        out << "{\n";
        out << "struct SAutoRegisterEnum_" << parsedClass.Name << "\n";
        out << "{\n";
        out << "    SAutoRegisterEnum_" << parsedClass.Name << "()\n";
        out << "    {\n";
        out << "        MHeaderTool_Generated_RegisterEnum_" << parsedClass.Name << "();\n";
        out << "    }\n";
        out << "};\n";
        out << "\n";
        out << "SAutoRegisterEnum_" << parsedClass.Name << " GAutoRegisterEnum_" << parsedClass.Name << ";\n";
        out << "} // namespace\n";
    }

    void GenerateStructHeader(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "#define MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "() \\\n";
        if (parsedClass.Properties.empty())
        {
            out << "    do { \\\n";
            out << "        (void)InClass; \\\n";
            out << "    } while (0)\n";
        }
        else
        {
            out << "    do { \\\n";
            for (const auto& prop : parsedClass.Properties)
            {
                out << "        " << BuildPropertyRegistrationLine(prop) << " \\\n";
            }
            out << "    } while (0)\n";
        }
        out << "\n";

        out << "inline MClass* MHeaderTool_Generated_RegisterStruct_" << parsedClass.Name << "()\n";
        out << "{\n";
        out << "    static MClass* Struct = nullptr;\n";
        out << "    if (!Struct)\n";
        out << "    {\n";
        out << "        Struct = new MClass();\n";
        out << "        Struct->SetMeta(\"" << parsedClass.Name << "\", \"" << parsedClass.HeaderPath.generic_string() << "\", nullptr, " << BuildClassKindExpr(parsedClass) << ");\n";
        out << "        Struct->SetKind(" << BuildClassKindExpr(parsedClass) << ");\n";
        out << "        Struct->SetCppTypeIndex(std::type_index(typeid(" << parsedClass.Name << ")));\n";
        out << "        Struct->SetConstructor<" << parsedClass.Name << ">();\n";
        out << "        using ThisClass = " << parsedClass.Name << ";\n";
        out << "        MClass* InClass = Struct;\n";
        out << "        MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "();\n";
        out << "        MObject::RegisterStruct(Struct);\n";
        out << "    }\n";
        out << "    return Struct;\n";
        out << "}\n";
    }

    void GenerateStructSource(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "namespace\n";
        out << "{\n";
        out << "struct SAutoRegisterStruct_" << parsedClass.Name << "\n";
        out << "{\n";
        out << "    SAutoRegisterStruct_" << parsedClass.Name << "()\n";
        out << "    {\n";
        out << "        MHeaderTool_Generated_RegisterStruct_" << parsedClass.Name << "();\n";
        out << "    }\n";
        out << "};\n\n";
        out << "SAutoRegisterStruct_" << parsedClass.Name << " GAutoRegisterStruct_" << parsedClass.Name << ";\n";
        out << "} // namespace\n";
    }

    void GenerateClassHeader(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        // 属性访问器
        if (!parsedClass.Properties.empty())
        {
            for (const auto& prop : parsedClass.Properties)
            {
                std::string accessorName = "Prop_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(prop.Name);
                out << "inline const MProperty* " << accessorName << "()\n";
                out << "{\n";
                out << "    static const MProperty* Prop = []() -> const MProperty*\n";
                out << "    {\n";
                out << "        MClass* ClassMeta = " << parsedClass.Name << "::StaticClass();\n";
                out << "        return ClassMeta ? ClassMeta->FindProperty(\"" << prop.Name << "\") : nullptr;\n";
                out << "    }();\n";
                out << "    return Prop;\n";
                out << "}\n";
                out << "\n";
            }
        }

        // 函数参数结构体
        for (const auto& func : parsedClass.Functions)
        {
            std::string paramStructName = "MHeaderTool_Params_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
            out << "struct " << paramStructName << "\n";
            out << "{\n";
            for (const auto& param : func.Params)
            {
                out << "    " << param.StorageType << " " << param.Name << " {};\n";
            }
            if (func.ReturnStorageType != "void" && func.Transport != "ServerCall")
            {
                out << "    " << func.ReturnStorageType << " ReturnValue {};\n";
            }
            out << "};\n";
            out << "\n";

            // Client binder
            if (func.Transport == "Client" || !func.MessageName.empty())
            {
                GenerateClientBinder(out, parsedClass, func);
            }

            // ClientCall handler
            if (func.Transport == "ClientCall")
            {
                GenerateClientCallHandler(out, parsedClass, func);
            }

            // ServerCall handler
            if (func.Transport == "ServerCall")
            {
                GenerateServerCallHandler(out, parsedClass, func);
            }

            // RPC
            if (func.bIsRpc)
            {
                GenerateRpcWrapper(out, parsedClass, func);
            }
        }

        // MHEADERTOOL_REGISTER_PROPERTIES_ 宏
        out << "#define MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "() \\\n";
        if (parsedClass.Properties.empty())
        {
            out << "    do { \\\n";
            out << "        (void)InClass; \\\n";
            out << "    } while (0)\n";
        }
        else
        {
            out << "    do { \\\n";
            for (const auto& prop : parsedClass.Properties)
            {
                out << "        " << BuildPropertyRegistrationLine(prop) << " \\\n";
            }
            out << "    } while (0)\n";
        }
        out << "\n";

        // MHEADERTOOL_REGISTER_FUNCTIONS_ 宏
        out << "#define MHEADERTOOL_REGISTER_FUNCTIONS_" << parsedClass.Name << "() \\\n";
        if (parsedClass.Functions.empty())
        {
            out << "    do { \\\n";
            out << "        (void)InClass; \\\n";
            out << "    } while (0)\n";
        }
        else
        {
            out << "    do { \\\n";
            for (const auto& func : parsedClass.Functions)
            {
                out << ReplaceAll(BuildFunctionRegistrationBlock(parsedClass, func), "\n", " \\\n") << " \\\n";
            }
            out << "    } while (0)\n";
        }
    }

    void GenerateClassSource(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        // RegisterAllProperties/RegisterAllFunctions/StaticClass
        out << "void " << parsedClass.Name << "::RegisterAllProperties(MClass* InClass)\n";
        out << "{\n";
        out << "    MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "();\n";
        out << "}\n";
        out << "\n";

        out << "void " << parsedClass.Name << "::RegisterAllFunctions(MClass* InClass)\n";
        out << "{\n";
        out << "    MHEADERTOOL_REGISTER_FUNCTIONS_" << parsedClass.Name << "();\n";
        out << "}\n";
        out << "\n";

        out << "MClass* " << parsedClass.Name << "::StaticClass()\n";
        out << "{\n";
        out << "    static MClass* Class = nullptr;\n";
        out << "    if (!Class)\n";
        out << "    {\n";
        out << "        Class = new MClass();\n";
        out << "        Class->SetMeta(\"" << parsedClass.Name << "\", \"" << parsedClass.HeaderPath.generic_string() << "\", nullptr, " << parsedClass.ClassFlagsExpr << ");\n";
        out << "        Class->SetKind(" << BuildClassKindExpr(parsedClass) << ");\n";
        out << "        Class->SetConstructor<" << parsedClass.Name << ">();\n";
        out << "        " << parsedClass.Name << "::RegisterAllProperties(Class);\n";
        out << "        " << parsedClass.Name << "::RegisterAllFunctions(Class);\n";
        out << "        MObject::RegisterClass(Class);\n";
        out << "    }\n";
        out << "    return Class;\n";
        out << "}\n";
        out << "\n";

        // 自动注册
        out << "namespace\n";
        out << "{\n";
        out << "struct SAutoRegisterClass_" << parsedClass.Name << "\n";
        out << "{\n";
        out << "    SAutoRegisterClass_" << parsedClass.Name << "()\n";
        out << "    {\n";
        out << "        " << parsedClass.Name << "::StaticClass();\n";
        out << "    }\n";
        out << "};\n\n";
        out << "SAutoRegisterClass_" << parsedClass.Name << " GAutoRegisterClass_" << parsedClass.Name << ";\n";
        out << "} // namespace\n";
    }

    void GenerateClientBinder(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        std::string paramStructName = "MHeaderTool_Params_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        std::string binderName = "MHeaderTool_BindClientParams_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);

        size_t injectedCount = 0;
        for (const auto& param : func.Params)
        {
            if (param.StorageType == "uint64" &&
                (param.Name == "ClientConnectionId" || param.Name == "ConnectionId"))
            {
                ++injectedCount;
            }
        }
        size_t payloadCount = func.Params.size() - injectedCount;

        out << "inline bool " << binderName << "(uint64 ConnectionId, const TByteArray& Payload, TByteArray& OutParamStorage)\n";
        out << "{\n";
        out << "    OutParamStorage.assign(sizeof(" << paramStructName << "), 0);\n";
        out << "    auto* Params = reinterpret_cast<" << paramStructName << "*>(OutParamStorage.data());\n";
        for (const auto& param : func.Params)
        {
            if (param.StorageType == "uint64" &&
                (param.Name == "ClientConnectionId" || param.Name == "ConnectionId"))
            {
                out << "    Params->" << param.Name << " = ConnectionId;\n";
            }
        }

        if (payloadCount == 0)
        {
            out << "    if (!Payload.empty())\n";
            out << "    {\n";
            out << "        LOG_WARN(\"Generated client binder expected empty payload\");\n";
            out << "        return false;\n";
            out << "    }\n";
        }
        else if (payloadCount == 1)
        {
            for (const auto& param : func.Params)
            {
                if (param.StorageType == "uint64" &&
                    (param.Name == "ClientConnectionId" || param.Name == "ConnectionId"))
                {
                    continue;
                }
                out << "    " << param.StorageType << " PayloadValue {};\n";
                out << "    auto ParseResult = ParsePayload(Payload, PayloadValue, \"" << func.Name << "\");\n";
                out << "    if (!ParseResult.IsOk()) return false;\n";
                out << "    Params->" << param.Name << " = std::move(PayloadValue);\n";
                break;
            }
        }
        out << "    return true;\n";
        out << "}\n";
        out << "\n";
    }

    void GenerateClientCallHandler(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        if (func.Params.size() < 2) return;

        std::string handlerName = "MHeaderTool_HandleClientCall_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        const auto& requestParam = func.Params[0];
        const auto& responseParam = func.Params[1];

        out << "inline EGeneratedClientCallHandlerResult " << handlerName
            << "(MObject* Object, uint64, const TByteArray& Payload, TByteArray& OutResponsePayload)\n";
        out << "{\n";
        out << "    auto* TypedObject = static_cast<" << parsedClass.Name << "*>(Object);\n";
        out << "    if (!TypedObject) return EGeneratedClientCallHandlerResult::Failed;\n";
        out << "    " << requestParam.StorageType << " RequestValue {};\n";
        out << "    auto ParseResult = ParsePayload(Payload, RequestValue, \"" << func.Name << "\");\n";
        out << "    if (!ParseResult.IsOk()) return EGeneratedClientCallHandlerResult::ParamBindingFailed;\n";
        out << "    " << responseParam.StorageType << " ResponseValue {};\n";
        out << "    TypedObject->" << func.Name << "(RequestValue, ResponseValue);\n";
        out << "    if (IsCurrentClientCallDeferred()) return EGeneratedClientCallHandlerResult::Deferred;\n";
        out << "    OutResponsePayload = BuildPayload(ResponseValue);\n";
        out << "    return EGeneratedClientCallHandlerResult::Responded;\n";
        out << "}\n";
        out << "\n";
    }

    void GenerateServerCallHandler(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        if (func.Params.empty()) return;

        std::string handlerName = "MHeaderTool_HandleServerCall_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        const auto& requestParam = func.Params[0];

        out << "inline bool " << handlerName << "(MObject* Object, const TByteArray& Payload)\n";
        out << "{\n";
        out << "    auto* TypedObject = static_cast<" << parsedClass.Name << "*>(Object);\n";
        out << "    if (!TypedObject) return false;\n";
        out << "    " << requestParam.StorageType << " RequestValue {};\n";
        out << "    auto ParseResult = ParsePayload(Payload, RequestValue, \"" << func.Name << "\");\n";
        out << "    if (!ParseResult.IsOk()) return false;\n";
        out << "    const SServerCallContext Context = CaptureCurrentServerCallContext();\n";
        out << "    if (!Context.IsValid()) return false;\n";
        out << "    return MServerCallAsyncSupport::StartDeferredServerCall(Context, TypedObject->" << func.Name << "(RequestValue), \"" << func.Name << "\");\n";
        out << "}\n";
        out << "\n";
    }

    void GenerateRpcWrapper(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        out << "namespace MRpc\n";
        out << "{\n";
        out << "namespace " << SanitizeIdentifier(parsedClass.Name) << "\n";
        out << "{\n";
        out << "inline bool " << func.Name << "(TByteArray& OutData";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Type << " " << param.Name;
        }
        out << ")\n";
        out << "{\n";
        out << "    return BuildRpcPayloadForRemoteCall(\"" << parsedClass.Name << "\", \"" << func.Name << "\", OutData";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Name;
        }
        out << ");\n";
        out << "}\n";
        out << "template<typename TConnection>\n";
        out << "inline bool " << func.Name << "(TConnection&& Connection";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Type << " " << param.Name;
        }
        out << ")\n";
        out << "{\n";
        out << "    TByteArray RpcPayload;\n";
        out << "    if (!" << func.Name << "(RpcPayload";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Name;
        }
        out << ")) return false;\n";
        out << "    return SendServerRpcMessage(std::forward<TConnection>(Connection), RpcPayload);\n";
        out << "}\n";
        out << "} // namespace " << SanitizeIdentifier(parsedClass.Name) << "\n";
        out << "} // namespace MRpc\n";
        out << "\n";
    }

    // 辅助函数
    std::string BuildPropertyRegistrationLine(const SParsedProperty& prop) const
    {
        std::string line = "auto* Prop = new TMemberProperty<ThisClass, " + prop.Type + ", &ThisClass::" + prop.Name + ">";
        line += "(\"" + prop.Name + "\", EPropertyType::" + InferPropertyKind(prop.Type) + ", " + BuildPropertyFlagsExpr(prop.MacroArgs) + ");";
        for (const auto& meta : prop.Metadata)
        {
            line += " Prop->SetMetadata(\"" + meta.Key + "\", \"" + meta.Value + "\");";
        }
        line += " InClass->RegisterProperty(Prop);";
        return line;
    }

    std::string BuildPropertyFlagsExpr(const std::string& macroArgs) const
    {
        auto args = SplitTopLevelArgs(macroArgs);
        std::vector<std::string> parts;
        for (const auto& arg : args)
        {
            if (arg.empty() || arg.find('=') != std::string::npos) continue;
            auto tokens = SplitTopLevelPipes(arg);
            for (const auto& token : tokens)
            {
                if (!token.empty())
                {
                    parts.push_back("static_cast<uint64>(EPropertyFlags::" + token + ")");
                }
            }
        }
        if (parts.empty()) return "EPropertyFlags::None";
        std::string expr = "static_cast<EPropertyFlags>(";
        for (size_t i = 0; i < parts.size(); ++i)
        {
            if (i > 0) expr += " | ";
            expr += parts[i];
        }
        expr += ")";
        return expr;
    }

    std::string BuildFunctionRegistrationBlock(const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        std::ostringstream out;
        std::string paramStructName = "MHeaderTool_Params_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        std::string reliableValue = func.bReliable ? "true" : "false";

        out << "    do {\n";

        if (func.Transport == "Client" || !func.MessageName.empty())
        {
            out << "        auto* Func = new MFUNC_OBJECT();\n";
            out << "        Func->Name = \"" << func.Name << "\";\n";
            out << "        Func->Flags = " << BuildFunctionFlagsExpr(func) << ";\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        Func->Transport = \"" << func.Transport << "\";\n";
            out << "        Func->MessageName = \"" << func.MessageName << "\";\n";
            out << "        Func->RouteName = \"" << func.Route << "\";\n";
            out << "        Func->TargetName = \"" << func.Target << "\";\n";
            out << "        Func->AuthMode = \"" << func.Auth << "\";\n";
            out << "        Func->WrapMode = \"" << func.Wrap << "\";\n";
            out << "        InClass->RegisterFunction(Func);\n";
        }
        else if (func.bIsRpc)
        {
            std::string rpcKind = func.RpcKind.empty() ? "Server" : func.RpcKind;
            out << "        auto* Func = CreateRpcFunction<&ThisClass::" << func.Name << ">(\"" << func.Name << "\", "
                << BuildFunctionFlagsExpr(func) << ", ERpcType::" << rpcKind << ", " << reliableValue;
            if (!func.Endpoint.empty())
            {
                out << ", EServerType::" << func.Endpoint;
            }
            out << ");\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        InClass->RegisterFunction(Func);\n";
        }
        else
        {
            out << "        auto* Func = CreateNativeFunction<&ThisClass::" << func.Name << ">(\"" << func.Name << "\", "
                << BuildFunctionFlagsExpr(func) << ");\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        InClass->RegisterFunction(Func);\n";
        }

        out << "    } while (0)";
        return out.str();
    }

    std::string BuildFunctionFlagsExpr(const SParsedFunction& func) const
    {
        std::vector<std::string> parts;
        auto tokens = SplitTopLevelArgs(func.MacroArgs);
        for (const auto& token : tokens)
        {
            if (token.empty() || token.find('=') != std::string::npos) continue;
            auto flagTokens = SplitTopLevelPipes(token);
            for (const auto& flagToken : flagTokens)
            {
                if (flagToken.empty() || flagToken == "NetServer" || flagToken == "NetClient" ||
                    flagToken == "Client" || flagToken == "ClientCall" || flagToken == "ServerCall" || flagToken == "RPC")
                {
                    continue;
                }
                parts.push_back("static_cast<uint32>(EFunctionFlags::" + flagToken + ")");
            }
        }
        if (func.bConst)
        {
            parts.push_back("static_cast<uint32>(EFunctionFlags::Const)");
        }
        if (parts.empty()) return "EFunctionFlags::None";
        std::string expr = "static_cast<EFunctionFlags>(";
        for (size_t i = 0; i < parts.size(); ++i)
        {
            if (i > 0) expr += " | ";
            expr += parts[i];
        }
        expr += ")";
        return expr;
    }

    std::string BuildClassKindExpr(const SParsedClass& parsedClass) const
    {
        if (parsedClass.Kind == EParsedTypeKind::Struct) return "EClassKind::Struct";
        if (parsedClass.ReflectionType == "Server") return "EClassKind::Server";
        if (parsedClass.ReflectionType == "Service") return "EClassKind::Service";
        if (parsedClass.ReflectionType == "Rpc") return "EClassKind::Rpc";
        return "EClassKind::Object";
    }

    std::string InferPropertyKind(const std::string& typeName) const
    {
        const std::string compact = ReplaceAll(Trim(typeName), " ", "");
        if (compact == "int8") return "Int8";
        if (compact == "int16") return "Int16";
        if (compact == "int32") return "Int32";
        if (compact == "int64") return "Int64";
        if (compact == "uint8") return "UInt8";
        if (compact == "uint16") return "UInt16";
        if (compact == "uint32") return "UInt32";
        if (compact == "uint64") return "UInt64";
        if (compact == "float") return "Float";
        if (compact == "double") return "Double";
        if (compact == "bool") return "Bool";
        if (compact == "MString") return "String";
        if (compact == "MName") return "Name";
        if (compact == "SVector") return "Vector";
        if (compact == "SRotator") return "Rotator";
        if (StartsWith(compact, "TVector<") || StartsWith(compact, "TByteArray<") ||
            StartsWith(compact, "TMap<") || StartsWith(compact, "TSet<"))
        {
            return "Array";
        }
        return "Struct";
    }

    std::string MakeIncludePathFromHeader(const fs::path& headerPath) const
    {
        fs::path includePath = headerPath;
        if (includePath.is_absolute())
        {
            std::error_code ec;
            includePath = fs::relative(includePath, fs::current_path(), ec);
            if (ec) includePath = headerPath.filename();
        }
        if (!includePath.empty() && includePath.begin()->string() == "Source")
        {
            includePath = fs::relative(includePath, "Source");
        }
        return includePath.generic_string();
    }

    const char* GetTypeKindName(EParsedTypeKind kind) const
    {
        switch (kind)
        {
        case EParsedTypeKind::Class: return "class";
        case EParsedTypeKind::Struct: return "struct";
        case EParsedTypeKind::Enum: return "enum";
        }
        return "unknown";
    }

    SOptions Options_;
};

}  // namespace MHeaderTool
