#pragma once

#include "Core/Types.h"
#include "Util/StringUtil.h"
#include <filesystem>
#include <sstream>
#include <regex>

namespace fs = std::filesystem;

namespace MHeaderTool
{

// ============================================================================
// Code Generator - 生成兼容原始格式的代码
// ============================================================================

class CodeGenerator
{
public:
    explicit CodeGenerator(const SOptions& options)
        : Options_(options)
    {
    }

    // 生成头文件内容
    std::string GenerateHeader(const SParsedClass& parsedClass) const
    {
        std::ostringstream out;

        out << "#pragma once\n";
        out << "// Generated by MHeaderTool\n";
        out << "// Source: " << parsedClass.HeaderPath.string() << "\n";
        out << "// Reflected " << GetTypeKindName(parsedClass.Kind) << ": " << parsedClass.Name << "\n";
        out << "\n";

        // 包含必要的头文件
        out << "#include \"Common/Runtime/Reflect/Reflection.h\"\n";
        out << "#include \"Common/Runtime/Async/MAsync.h\"\n";
        out << "#include \"Common/Net/Rpc/RpcClientCall.h\"\n";
        out << "#include \"" << MakeIncludePathFromHeader(parsedClass.HeaderPath) << "\"\n";
        out << "\n";

        if (parsedClass.Kind == EParsedTypeKind::Enum)
        {
            GenerateEnumHeader(out, parsedClass);
        }
        else if (parsedClass.Kind == EParsedTypeKind::Struct)
        {
            GenerateStructHeader(out, parsedClass);
        }
        else
        {
            GenerateClassHeader(out, parsedClass);
        }

        return out.str();
    }

    // 生成源文件内容
    std::string GenerateSource(const SParsedClass& parsedClass) const
    {
        std::ostringstream out;

        std::string includeName = MakeIncludePathFromHeader(parsedClass.HeaderPath);
        std::string generatedHeader = SanitizeIdentifier(parsedClass.Name) + ".mgenerated.h";

        out << "// Generated by MHeaderTool\n";
        out << "// Source: " << parsedClass.HeaderPath.string() << "\n";
        out << "#include \"" << generatedHeader << "\"\n";
        out << "#include \"" << includeName << "\"\n";
        out << "\n\n";

        if (parsedClass.Kind == EParsedTypeKind::Enum)
        {
            GenerateEnumSource(out, parsedClass);
        }
        else if (parsedClass.Kind == EParsedTypeKind::Struct)
        {
            GenerateStructSource(out, parsedClass);
        }
        else
        {
            GenerateClassSource(out, parsedClass);
        }

        return out.str();
    }

private:
    void GenerateEnumHeader(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        // For nested scoped enums (inside classes), we can't generate registration code
        // because the enum is private and can't be accessed externally
        if (parsedClass.bScopedEnum && parsedClass.Owner.empty())
        {
            // Generate a no-op stub that returns nullptr
            out << "// Nested scoped enum - cannot generate registration\n";
            out << "inline MEnum* MHeaderTool_Generated_RegisterEnum_" << parsedClass.Name << "()\n";
            out << "{\n";
            out << "    return nullptr;\n";
            out << "}\n";
            return;
        }

        out << "inline MEnum* MHeaderTool_Generated_RegisterEnum_" << parsedClass.Name << "()\n";
        out << "{\n";
        out << "    static MEnum* Enum = nullptr;\n";
        out << "    if (!Enum)\n";
        out << "    {\n";
        out << "        Enum = new MEnum(\"" << parsedClass.Name << "\", \"" << parsedClass.HeaderPath.generic_string() << "\", std::type_index(typeid(" << parsedClass.Name << ")));\n";
        for (size_t i = 0; i < parsedClass.EnumValues.size(); ++i)
        {
            std::string value = parsedClass.EnumValues[i];
            if (parsedClass.bScopedEnum && !parsedClass.Owner.empty())
            {
                // For scoped enums in namespaces, try EnumName::Value
                out << "        Enum->AddValue(\"" << value << "\", static_cast<int64>(" << parsedClass.Name << "::" << value << "));\n";
            }
            else if (parsedClass.bScopedEnum && parsedClass.Owner.empty())
            {
                // Nested scoped enum inside a class - skip value registration
                // The enum type is registered but values can't be accessed externally
                continue;
            }
            else
            {
                out << "        Enum->AddValue(\"" << value << "\", static_cast<int64>(" << value << "));\n";
            }
        }
        out << "        MObject::RegisterEnum(Enum);\n";
        out << "    }\n";
        out << "    return Enum;\n";
        out << "}\n";
    }

    void GenerateEnumSource(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "namespace\n";
        out << "{\n";
        out << "struct SAutoRegisterEnum_" << parsedClass.Name << "\n";
        out << "{\n";
        out << "    SAutoRegisterEnum_" << parsedClass.Name << "()\n";
        out << "    {\n";
        out << "        MHeaderTool_Generated_RegisterEnum_" << parsedClass.Name << "();\n";
        out << "    }\n";
        out << "};\n";
        out << "\n";
        out << "SAutoRegisterEnum_" << parsedClass.Name << " GAutoRegisterEnum_" << parsedClass.Name << ";\n";
        out << "} // namespace\n";
    }

    void GenerateStructHeader(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "#define MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "() \\\n";
        if (parsedClass.Properties.empty())
        {
            out << "    do { (void)InClass; } while(0)\n";
        }
        else
        {
            out << "    do { \\\n";
            for (const auto& prop : parsedClass.Properties)
            {
                out << "        " << BuildPropertyRegistrationLine(prop) << " \\\n";
            }
            out << "    } while(0)\n";
        }
        out << "\n";

        out << "inline MClass* MHeaderTool_Generated_RegisterStruct_" << parsedClass.Name << "()\n";
        out << "{\n";
        out << "    static MClass* Struct = nullptr;\n";
        out << "    if (!Struct)\n";
        out << "    {\n";
        out << "        Struct = new MClass();\n";
        out << "        Struct->SetMeta(\"" << parsedClass.Name << "\", \"" << parsedClass.HeaderPath.generic_string() << "\", nullptr, static_cast<uint32>(" << BuildClassKindExpr(parsedClass) << "));\n";
        out << "        Struct->SetKind(" << BuildClassKindExpr(parsedClass) << ");\n";
        out << "        Struct->SetCppTypeIndex(std::type_index(typeid(" << parsedClass.Name << ")));\n";
        out << "        Struct->SetConstructor<" << parsedClass.Name << ">();\n";
        out << "        using ThisClass = " << parsedClass.Name << ";\n";
        out << "        MClass* InClass = Struct;\n";
        out << "        MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "();\n";
        out << "        MObject::RegisterStruct(Struct);\n";
        out << "    }\n";
        out << "    return Struct;\n";
        out << "}\n";
    }

    void GenerateStructSource(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        out << "namespace\n";
        out << "{\n";
        out << "struct SAutoRegisterStruct_" << parsedClass.Name << "\n";
        out << "{\n";
        out << "    SAutoRegisterStruct_" << parsedClass.Name << "()\n";
        out << "    {\n";
        out << "        MHeaderTool_Generated_RegisterStruct_" << parsedClass.Name << "();\n";
        out << "    }\n";
        out << "};\n\n";
        out << "SAutoRegisterStruct_" << parsedClass.Name << " GAutoRegisterStruct_" << parsedClass.Name << ";\n";
        out << "} // namespace\n";
    }

    void GenerateClassHeader(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        // 属性访问器
        if (!parsedClass.Properties.empty())
        {
            for (const auto& prop : parsedClass.Properties)
            {
                std::string accessorName = "Prop_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(prop.Name);
                out << "inline const MProperty* " << accessorName << "()\n";
                out << "{\n";
                out << "    static const MProperty* Prop = []() -> const MProperty*\n";
                out << "    {\n";
                out << "        MClass* ClassMeta = " << parsedClass.Name << "::StaticClass();\n";
                out << "        return ClassMeta ? ClassMeta->FindProperty(\"" << prop.Name << "\") : nullptr;\n";
                out << "    }();\n";
                out << "    return Prop;\n";
                out << "}\n";
                out << "\n";
            }
        }

        // 函数参数结构体
        for (const auto& func : parsedClass.Functions)
        {
            std::string paramStructName = "MHeaderTool_Params_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
            out << "struct " << paramStructName << "\n";
            out << "{\n";
            for (const auto& param : func.Params)
            {
                out << "    " << param.StorageType << " " << param.Name << " {};\n";
            }
            if (func.ReturnStorageType != "void" && func.Transport != "ServerCall")
            {
                out << "    " << func.ReturnStorageType << " ReturnValue {};\n";
            }
            out << "};\n";
            out << "\n";

            // Client binder
            if (func.Transport == "Client" || !func.MessageName.empty())
            {
                GenerateClientBinder(out, parsedClass, func);
            }

            // step-2: ClientCall handler emit 路径已 no-op。原 client dispatch 由
            // Gateway 端 MClientManifest 反射 + MRpcChannel::Call 接管,不再走
            // MFunctionObject::ClientCallHandler 虚表。
            if (func.Transport == "ClientCall")
            {
                GenerateClientCallHandler(out, parsedClass, func);
            }

            // ServerCall handler
            if (func.Transport == "ServerCall")
            {
                GenerateServerCallHandler(out, parsedClass, func);
            }

            // RPC
            if (func.bIsRpc)
            {
                GenerateRpcWrapper(out, parsedClass, func);
            }
        }

        // MHEADERTOOL_REGISTER_PROPERTIES_ 宏
        out << "#define MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "() \\\n";
        if (parsedClass.Properties.empty())
        {
            out << "    do { (void)InClass; } while(0)\n";
        }
        else
        {
            out << "    do { \\\n";
            for (const auto& prop : parsedClass.Properties)
            {
                out << "        " << BuildPropertyRegistrationLine(prop) << " \\\n";
            }
            out << "    } while(0)\n";
        }
        out << "\n";

        // MHEADERTOOL_REGISTER_FUNCTIONS_ 宏
        out << "#define MHEADERTOOL_REGISTER_FUNCTIONS_" << parsedClass.Name << "() \\\n";
        if (parsedClass.Functions.empty())
        {
            out << "    (void)InClass\n";
        }
        else
        {
            for (size_t i = 0; i < parsedClass.Functions.size(); ++i)
            {
                const auto& func = parsedClass.Functions[i];
                std::string block = ReplaceAll(BuildFunctionRegistrationBlock(parsedClass, func), "\n", " \\\n");
                // Remove trailing backslash from block since we'll add our own
                if (!block.empty() && block.back() == '\\')
                {
                    block.pop_back();
                }
                out << "    " << block;
                if (i < parsedClass.Functions.size() - 1)
                {
                    out << " \\\n";
                }
                else
                {
                    out << "\n";
                }
            }
        }
    }

    void GenerateClassSource(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        // RegisterAllProperties/RegisterAllFunctions/StaticClass
        out << "void " << parsedClass.Name << "::RegisterAllProperties(MClass* InClass)\n";
        out << "{\n";
        out << "    MHEADERTOOL_REGISTER_PROPERTIES_" << parsedClass.Name << "();\n";
        out << "}\n";
        out << "\n";

        out << "void " << parsedClass.Name << "::RegisterAllFunctions(MClass* InClass)\n";
        out << "{\n";
        out << "    MHEADERTOOL_REGISTER_FUNCTIONS_" << parsedClass.Name << "();\n";
        out << "}\n";
        out << "\n";

        out << "MClass* " << parsedClass.Name << "::StaticClass()\n";
        out << "{\n";
        out << "    static MClass* Class = nullptr;\n";
        out << "    if (!Class)\n";
        out << "    {\n";
        out << "        Class = new MClass();\n";
        out << "        Class->SetMeta(\"" << parsedClass.Name << "\", \"" << parsedClass.HeaderPath.generic_string() << "\", nullptr, static_cast<uint32>(" << BuildClassKindExpr(parsedClass) << "));\n";
        out << "        Class->SetKind(" << BuildClassKindExpr(parsedClass) << ");\n";
        out << "        Class->SetConstructor<" << parsedClass.Name << ">();\n";
        out << "        " << parsedClass.Name << "::RegisterAllProperties(Class);\n";
        out << "        " << parsedClass.Name << "::RegisterAllFunctions(Class);\n";
        out << "        MObject::RegisterClass(Class);\n";
        out << "    }\n";
        out << "    return Class;\n";
        out << "}\n";
        out << "\n";

        // 为 ServerCall 代理类生成函数实现
        GenerateServerCallProxyImplementations(out, parsedClass);

        // 自动注册
        out << "namespace\n";
        out << "{\n";
        out << "struct SAutoRegisterClass_" << parsedClass.Name << "\n";
        out << "{\n";
        out << "    SAutoRegisterClass_" << parsedClass.Name << "()\n";
        out << "    {\n";
        out << "        " << parsedClass.Name << "::StaticClass();\n";
        out << "    }\n";
        out << "};\n\n";
        out << "SAutoRegisterClass_" << parsedClass.Name << " GAutoRegisterClass_" << parsedClass.Name << ";\n";
        out << "} // namespace\n";
    }

    void GenerateClientBinder(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        std::string paramStructName = "MHeaderTool_Params_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        std::string binderName = "MHeaderTool_BindClientParams_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);

        size_t injectedCount = 0;
        for (const auto& param : func.Params)
        {
            if (param.StorageType == "uint64" &&
                (param.Name == "ClientConnectionId" || param.Name == "ConnectionId"))
            {
                ++injectedCount;
            }
        }
        size_t payloadCount = func.Params.size() - injectedCount;

        out << "inline bool " << binderName << "(uint64 ConnectionId, const TByteArray& Payload, TByteArray& OutParamStorage)\n";
        out << "{\n";
        out << "    OutParamStorage.assign(sizeof(" << paramStructName << "), 0);\n";
        out << "    auto* Params = reinterpret_cast<" << paramStructName << "*>(OutParamStorage.data());\n";
        for (const auto& param : func.Params)
        {
            if (param.StorageType == "uint64" &&
                (param.Name == "ClientConnectionId" || param.Name == "ConnectionId"))
            {
                out << "    Params->" << param.Name << " = ConnectionId;\n";
            }
        }

        if (payloadCount == 0)
        {
            out << "    if (!Payload.empty())\n";
            out << "    {\n";
            out << "        LOG_WARN(\"Generated client binder expected empty payload\");\n";
            out << "        return false;\n";
            out << "    }\n";
        }
        else if (payloadCount == 1)
        {
            for (const auto& param : func.Params)
            {
                if (param.StorageType == "uint64" &&
                    (param.Name == "ClientConnectionId" || param.Name == "ConnectionId"))
                {
                    continue;
                }
                out << "    " << param.StorageType << " PayloadValue {};\n";
                out << "    auto ParseResult = ParsePayload(Payload, PayloadValue, \"" << func.Name << "\");\n";
                out << "    if (!ParseResult.IsOk()) return false;\n";
                out << "    Params->" << param.Name << " = std::move(PayloadValue);\n";
                break;
            }
        }
        out << "    return true;\n";
        out << "}\n";
        out << "\n";
    }

    // step-2: ClientCall 的 MHeaderTool emit 路径已删除。原 GenerateClientCallHandler
    // 依赖 EGeneratedClientCallHandlerResult / IsCurrentClientCallDeferred /
    // MFunctionObject::ClientCallHandler,这些字段都随 ClientProtocol 重构拆掉。
    // 后续如果有 MFUNCTION(Async, CallClient) 这类下行通知的需求(本工作树后续
    // task 引入),会走 GenerateClientDownlinkStub 那条新路径,emit 到
    // MClientDownlinkManifest + 静态 stub 函数,而不是 emit ClientCallHandler
    // 虚表项。
    void GenerateClientCallHandler(std::ostringstream& /*out*/, const SParsedClass& /*parsedClass*/, const SParsedFunction& /*func*/) const
    {
        // no-op: client-side call dispatch 由 Gateway 反射接管,这里不再 emit
    }

    void GenerateServerCallHandler(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        if (func.Params.empty()) return;

        std::string handlerName = "MHeaderTool_HandleServerCall_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        const auto& requestParam = func.Params[0];

        // Extract raw response type from `SFutureResult<FResp>` (CodeGenerator.h:766 ExtractResponseType).
        const std::string responseType = ExtractResponseType(func.ReturnStorageType);

        out << "inline SFutureResult<TByteArray> " << handlerName << "(MObject* Object, const TByteArray& Payload)\n";
        out << "{\n";
        out << "    auto* TypedObject = static_cast<" << parsedClass.Name << "*>(Object);\n";
        out << "    if (!TypedObject)\n";
        out << "    {\n";
        out << "        return MServerCallAsyncSupport::MakeErrorFuture<TByteArray>(MString(\"server_call_invalid_object\"));\n";
        out << "    }\n";
        out << "    " << requestParam.StorageType << " RequestValue {};\n";
        out << "    auto ParseResult = ParsePayload(Payload, RequestValue, \"" << func.Name << "\");\n";
        out << "    if (!ParseResult.IsOk())\n";
        out << "    {\n";
        out << "        return MServerCallAsyncSupport::MakeErrorFuture<TByteArray>(ParseResult.GetError(), MString());\n";
        out << "    }\n";
        out << "    const SServerCallContext Context = CaptureCurrentServerCallContext();\n";
        out << "    (void)Context;\n";
        out << "    SFutureResult<" << responseType << "> Inner = TypedObject->" << func.Name << "(std::move(RequestValue));\n";
        out << "    MPromise<TResult<TByteArray, FAppError>> OutPromise;\n";
        out << "    auto OutFuture = OutPromise.GetFuture();\n";
        out << "    if (Inner.IsReady())\n";
        out << "    {\n";
        out << "        TResult<" << responseType << ", FAppError> R = Inner.GetResult();\n";
        out << "        if (R.IsErr()) OutPromise.SetValue(TResult<TByteArray, FAppError>::Err(R.GetError()));\n";
        out << "        else OutPromise.SetValue(TResult<TByteArray, FAppError>::Ok(BuildPayload(R.GetValue())));\n";
        out << "        return SFutureResult<TByteArray>(OutFuture);\n";
        out << "    }\n";
        out << "    Inner.Then([OutPromise](MFuture<TResult<" << responseType << ", FAppError>> F) mutable\n";
        out << "    {\n";
        out << "        TResult<" << responseType << ", FAppError> R = F.Get();\n";
        out << "        if (R.IsErr()) OutPromise.SetValue(TResult<TByteArray, FAppError>::Err(R.GetError()));\n";
        out << "        else OutPromise.SetValue(TResult<TByteArray, FAppError>::Ok(BuildPayload(R.GetValue())));\n";
        out << "    });\n";
        out << "    return SFutureResult<TByteArray>(OutFuture);\n";
        out << "}\n";
        out << "\n";
    }

    void GenerateRpcWrapper(std::ostringstream& out, const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        out << "namespace MRpc\n";
        out << "{\n";
        out << "namespace " << SanitizeIdentifier(parsedClass.Name) << "\n";
        out << "{\n";
        out << "inline bool " << func.Name << "(TByteArray& OutData";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Type << " " << param.Name;
        }
        out << ")\n";
        out << "{\n";
        out << "    return BuildRpcPayloadForRemoteCall(\"" << parsedClass.Name << "\", \"" << func.Name << "\", OutData";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Name;
        }
        out << ");\n";
        out << "}\n";
        out << "template<typename TConnection>\n";
        out << "inline bool " << func.Name << "(TConnection&& Connection";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Type << " " << param.Name;
        }
        out << ")\n";
        out << "{\n";
        out << "    TByteArray RpcPayload;\n";
        out << "    if (!" << func.Name << "(RpcPayload";
        for (const auto& param : func.Params)
        {
            out << ", " << param.Name;
        }
        out << ")) return false;\n";
        out << "    return SendServerRpcMessage(std::forward<TConnection>(Connection), RpcPayload);\n";
        out << "}\n";
        out << "} // namespace " << SanitizeIdentifier(parsedClass.Name) << "\n";
        out << "} // namespace MRpc\n";
        out << "\n";
    }

    void GenerateServerCallProxyImplementations(std::ostringstream& out, const SParsedClass& parsedClass) const
    {
        // 检查是否有 ServerCall 类型的函数
        bool hasServerCall = false;
        for (const auto& func : parsedClass.Functions)
        {
            if (func.Transport == "ServerCall")
            {
                hasServerCall = true;
                break;
            }
        }

        if (!hasServerCall)
        {
            return;
        }

        // 检查是否继承自 MServerCallProxyBase
        bool isProxyClass = false;
        for (const auto& parent : parsedClass.AllParentClasses)
        {
            if (parent == "MServerCallProxyBase")
            {
                isProxyClass = true;
                break;
            }
        }

        // 如果不是代理类，不生成 CallRemoteByName 实现
        if (!isProxyClass)
        {
            return;
        }

        // 生成 ServerCall 函数的实现
        for (const auto& func : parsedClass.Functions)
        {
            if (func.Transport != "ServerCall")
            {
                continue;
            }

            if (func.Params.empty())
            {
                continue;
            }

            // 获取请求参数（第一个参数是 Request）
            const auto& requestParam = func.Params[0];

            // 生成函数实现：调用 CallRemoteByName
            // TResponse 应该是原始响应类型（如 FPlayerEnterWorldResponse），CallRemoteByName 会内部包装到 TResult<>
            const std::string responseType = ExtractResponseType(func.ReturnStorageType);
            out << func.ReturnStorageType << " " << parsedClass.Name << "::" << func.Name << "(" << requestParam.StorageType << " const& Request)\n";
            out << "{\n";
            out << "    return CallRemoteByName<" << responseType << ">(\"" << func.Name << "\", Request);\n";
            out << "}\n";
            out << "\n";
        }
    }

    // 辅助函数
    std::string BuildPropertyRegistrationLine(const SParsedProperty& prop) const
    {
        std::string line = "auto* Prop_" + prop.Name + " = new TMemberProperty<ThisClass, " + prop.Type + ", &ThisClass::" + prop.Name + ">";
        line += "(\"" + prop.Name + "\", EPropertyType::" + InferPropertyKind(prop.Type) + ", " + BuildPropertyFlagsExpr(prop.MacroArgs) + ");";
        for (const auto& meta : prop.Metadata)
        {
            line += " Prop_" + prop.Name + "->SetMetadata(\"" + meta.Key + "\", \"" + meta.Value + "\");";
        }
        line += " InClass->RegisterProperty(Prop_" + prop.Name + ");";
        return line;
    }

    std::string BuildPropertyFlagsExpr(const std::string& macroArgs) const
    {
        auto args = SplitTopLevelArgs(macroArgs);
        std::vector<std::string> parts;
        for (const auto& arg : args)
        {
            if (arg.empty() || arg.find('=') != std::string::npos) continue;
            auto tokens = SplitTopLevelPipes(arg);
            for (const auto& token : tokens)
            {
                if (!token.empty())
                {
                    parts.push_back("static_cast<uint64>(EPropertyFlags::" + token + ")");
                }
            }
        }
        if (parts.empty()) return "EPropertyFlags::None";
        std::string expr = "static_cast<EPropertyFlags>(";
        for (size_t i = 0; i < parts.size(); ++i)
        {
            if (i > 0) expr += " | ";
            expr += parts[i];
        }
        expr += ")";
        return expr;
    }

    std::string BuildFunctionRegistrationBlock(const SParsedClass& parsedClass, const SParsedFunction& func) const
    {
        std::ostringstream out;
        std::string paramStructName = "MHeaderTool_Params_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
        std::string reliableValue = func.bReliable ? "true" : "false";

        // No do-while wrapper - we're inside a macro
        out << "    {\n";

        // step-2: 客户端 dispatch 字段(MessageName/RouteName/TargetName/AuthMode/
        // WrapMode)整段从 MFunctionObject 删除。Client / ClientCall 这两条
        // transport 也不再走 RegisterFunction 直接 emit 字段;改由后续 task
        // 引入的 GenerateClientDownlinkStub 走 MClientDownlinkManifest 路径。
        // 这里把 Client 路径保留最小 stub 形态(Transport 字段仍留 Class.h,
        // 因为 ServerCall 也用它)。
        if (func.Transport == "Client" || !func.MessageName.empty())
        {
            out << "        auto* Func = new MFUNC_OBJECT();\n";
            out << "        Func->Name = \"" << func.Name << "\";\n";
            out << "        Func->Flags = " << BuildFunctionFlagsExpr(func) << ";\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        Func->Transport = \"" << func.Transport << "\";\n";
            out << "        InClass->RegisterFunction(Func);\n";
        }
        else if (func.bIsRpc && func.Transport != "ServerCall")
        {
            std::string rpcKind = func.RpcKind.empty() ? "Server" : func.RpcKind;
            out << "        auto* Func = CreateRpcFunction<&ThisClass::" << func.Name << ">(\"" << func.Name << "\", "
                << BuildFunctionFlagsExpr(func) << ", ERpcType::" << rpcKind << ", " << reliableValue;
            if (!func.Endpoint.empty())
            {
                out << ", EServerType::" << func.Endpoint;
            }
            out << ");\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        InClass->RegisterFunction(Func);\n";
        }
        else if (func.Transport == "ServerCall")
        {
            // ServerCall transport: wire the generated handler (decodes request,
            // calls the typed method, bridges SFutureResult<TResp> ->
            // SFutureResult<TByteArray> via ready/pending branches — see
            // GenerateServerCallHandler) onto MFunctionObject::ServerCallHandler.
            // Applies uniformly to MFUNCTION(ServerCall) and MFUNCTION(ServerCall, Async);
            // the Async flag is preserved on the parsed function for P3 codegen.
            std::string handlerName = "MHeaderTool_HandleServerCall_" + SanitizeIdentifier(parsedClass.Name) + "_" + SanitizeIdentifier(func.Name);
            out << "        auto* Func = new MFUNC_OBJECT();\n";
            out << "        Func->Name = \"" << func.Name << "\";\n";
            out << "        Func->Flags = " << BuildFunctionFlagsExpr(func) << ";\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        Func->Transport = \"" << func.Transport << "\";\n";
            out << "        Func->ServerCallHandler = " << handlerName << ";\n";
            out << "        InClass->RegisterFunction(Func);\n";
        }
        else if (func.Transport != "ServerCall")
        {
            out << "        auto* Func = CreateNativeFunction<&ThisClass::" << func.Name << ">(\"" << func.Name << "\", "
                << BuildFunctionFlagsExpr(func) << ");\n";
            out << "        Func->ParamSize = sizeof(" << paramStructName << ");\n";
            for (const auto& param : func.Params)
            {
                out << "        Func->Params.push_back(CreateOffsetProperty<" << param.StorageType << ">(\""
                    << param.Name << "\", EPropertyType::" << param.PropertyKind << ", offsetof("
                    << paramStructName << ", " << param.Name << ")));\n";
            }
            out << "        InClass->RegisterFunction(Func);\n";
        }

        out << "    }";
        return out.str();
    }

    std::string BuildFunctionFlagsExpr(const SParsedFunction& func) const
    {
        std::vector<std::string> parts;
        auto tokens = SplitTopLevelArgs(func.MacroArgs);
        for (const auto& token : tokens)
        {
            if (token.empty() || token.find('=') != std::string::npos) continue;
            auto flagTokens = SplitTopLevelPipes(token);
            for (const auto& flagToken : flagTokens)
            {
                // Skip tokens that are transport / role labels (handled elsewhere
                // by Func->Transport / Func->bIsAsync / Func->bIsClient / etc.),
                // not EFunctionFlags enum values. Most importantly:
                //   - "Async" -> captured in parsed->bIsAsync (P3 codegen consumer);
                //     P2 treats it identically to non-Async ServerCall (the
                //     GenerateServerCallHandler already supports pending futures).
                //   - "ServerCall" / "ClientCall" / transport labels -> emit
                //     separately as Func->Transport, not in the flags bitmask.
                if (flagToken.empty() || flagToken == "Async" ||
                    flagToken == "NetServer" || flagToken == "NetClient" ||
                    flagToken == "Client" || flagToken == "ClientCall" || flagToken == "ServerCall" || flagToken == "RPC")
                {
                    continue;
                }
                parts.push_back("static_cast<uint32>(EFunctionFlags::" + flagToken + ")");
            }
        }
        if (func.bConst)
        {
            parts.push_back("static_cast<uint32>(EFunctionFlags::Const)");
        }
        if (parts.empty()) return "EFunctionFlags::None";
        std::string expr = "static_cast<EFunctionFlags>(";
        for (size_t i = 0; i < parts.size(); ++i)
        {
            if (i > 0) expr += " | ";
            expr += parts[i];
        }
        expr += ")";
        return expr;
    }

    std::string BuildClassKindExpr(const SParsedClass& parsedClass) const
    {
        if (parsedClass.Kind == EParsedTypeKind::Struct) return "EClassKind::Struct";
        if (parsedClass.ReflectionType == "Server") return "EClassKind::Server";
        if (parsedClass.ReflectionType == "Service") return "EClassKind::Service";
        if (parsedClass.ReflectionType == "Rpc") return "EClassKind::Rpc";
        return "EClassKind::Object";
    }

    std::string InferPropertyKind(const std::string& typeName) const
    {
        const std::string compact = ReplaceAll(Trim(typeName), " ", "");
        if (compact == "int8") return "Int8";
        if (compact == "int16") return "Int16";
        if (compact == "int32") return "Int32";
        if (compact == "int64") return "Int64";
        if (compact == "uint8") return "UInt8";
        if (compact == "uint16") return "UInt16";
        if (compact == "uint32") return "UInt32";
        if (compact == "uint64") return "UInt64";
        if (compact == "float") return "Float";
        if (compact == "double") return "Double";
        if (compact == "bool") return "Bool";
        if (compact == "MString") return "String";
        if (compact == "MName") return "Name";
        if (compact == "SVector") return "Vector";
        if (compact == "SRotator") return "Rotator";
        if (StartsWith(compact, "TVector<") || StartsWith(compact, "TByteArray<") ||
            StartsWith(compact, "TMap<") || StartsWith(compact, "TSet<"))
        {
            return "Array";
        }
        return "Struct";
    }

    std::string MakeIncludePathFromHeader(const fs::path& headerPath) const
    {
        fs::path includePath = headerPath;
        if (includePath.is_absolute())
        {
            std::error_code ec;
            includePath = fs::relative(includePath, fs::current_path(), ec);
            if (ec) includePath = headerPath.filename();
        }
        if (!includePath.empty() && includePath.begin()->string() == "Source")
        {
            includePath = fs::relative(includePath, "Source");
        }
        return includePath.generic_string();
    }

    const char* GetTypeKindName(EParsedTypeKind kind) const
    {
        switch (kind)
        {
        case EParsedTypeKind::Class: return "class";
        case EParsedTypeKind::Struct: return "struct";
        case EParsedTypeKind::Enum: return "enum";
        }
        return "unknown";
    }

    // 从 MFuture<TResult<T, E>> 中提取 T（原始响应类型）
    std::string ExtractResponseType(const std::string& returnType) const
    {
        // Strip SFutureResult<X> / MFuture<TResult<X, Y>> wrappers (and any
        // combination), returning the raw response type X. Used by the
        // generated ServerCall handler so it can call the typed method and
        // pattern-match on `TResult<RespType, FAppError>`.
        const std::string sfPrefix = "SFutureResult<";
        const std::string mfPrefix  = "MFuture<TResult<";

        std::string T = returnType;
        // Outer wrapper: SFutureResult<Inner>
        if (T.rfind(sfPrefix, 0) == 0 && T.back() == '>')
        {
            std::string Inner = T.substr(sfPrefix.size(), T.size() - sfPrefix.size() - 1);
            return ExtractResponseType(Inner);
        }
        // Inner wrapper: MFuture<TResult<X, Y>>
        if (T.rfind(mfPrefix, 0) == 0 && T.back() == '>')
        {
            std::string Inner = T.substr(mfPrefix.size(), T.size() - mfPrefix.size() - 1);
            size_t comma = Inner.find(',');
            if (comma != std::string::npos)
            {
                return Inner.substr(0, comma);
            }
        }
        return T;
    }

    SOptions Options_;
};

}  // namespace MHeaderTool
