#include "LuaBindEmitter.h"
#include "Core/Types.h"

#include <fstream>
#include <sstream>

namespace MHeaderTool {

    namespace {

        // 把 SParsedType 字符串("int32_t", "double" 等)转成 lua-language-server/Teal 类型名
        MString MapTealType(const MString& CppType) {
            if (CppType == "int8_t" || CppType == "int16_t" || CppType == "int32_t" || CppType == "int64_t") return "integer";
            if (CppType == "uint8_t" || CppType == "uint16_t" || CppType == "uint32_t" || CppType == "uint64_t") return "integer";
            if (CppType == "float" || CppType == "double") return "number";
            if (CppType == "bool") return "boolean";
            if (CppType == "MString") return "string";
            if (CppType == "void") return "nil";
            return "any";
        }

    } // namespace

    void LuaBindEmitter::Run(const std::filesystem::path& OutDir, const TVector<SParsedClass>& Classes) {
        std::filesystem::create_directories(OutDir);

        for (const SParsedClass& Cls : Classes) {
            // 跳过没有 LuaBind 方法的类
            bool bHasLuaBind = false;
            for (const auto& Fn : Cls.Functions) {
                if (Fn.Transport == "LuaBind") {
                    bHasLuaBind = true;
                    break;
                }
            }
            if (!bHasLuaBind)
                continue;

            std::filesystem::path LuaFile  = OutDir / (Cls.Name + ".lua");
            std::filesystem::path TealFile = OutDir / (Cls.Name + ".d.tl");

            // ---- emit .lua ----
            // Phase 1: 静态 dispatch + 4 primitive args/return(self=nullptr)
            // 业务 Lua 写 M_TestClass.Add(2, 3) 真正调到 C++ NativeInvoke
            std::ofstream Out(LuaFile);
            Out << "-- Auto-generated by MHeaderTool LuaBindEmitter\n";
            Out << "-- Source class: " << Cls.Name << "\n";
            Out << "-- DO NOT EDIT — 改 " << Cls.Name << " 的 MFUNCTION 注解后跑 mht 重生\n";
            Out << "--\n";
            Out << "-- Runtime bridge 由 MLuaBridge::Install 提供(M.InvokeStatic 全局)\n";
            Out << "-- (Lua 端不再 require 任何 module,M_*/M 全局已由 C 端 push)\n\n";
            Out << "local M_" << Cls.Name << " = {}\n\n";

            for (const auto& Fn : Cls.Functions) {
                if (Fn.Transport != "LuaBind")
                    continue;
                Out << "function M_" << Cls.Name << "." << Fn.Name << "(...)\n";
                Out << "    return M.InvokeStatic(\"" << Cls.Name << "\", \"" << Fn.Name << "\", {...})\n";
                Out << "end\n\n";
            }

            Out << "return M_" << Cls.Name << "\n";

            // ---- emit .d.tl ----
            // 加 method record(原本只 emit property field)
            std::ofstream Teal(TealFile);
            Teal << "---@meta mession\n";
            Teal << "-- Auto-generated by MHeaderTool LuaBindEmitter (Teal type checker hint)\n";
            Teal << "local record M_" << Cls.Name << "\n";
            Teal << "    userdata\n\n";
            for (const auto& Fn : Cls.Functions) {
                if (Fn.Transport != "LuaBind")
                    continue;
                Teal << "    " << Fn.Name << ": function(";
                bool bFirst = true;
                if (Fn.Params.empty()) {
                    Teal << "...";
                } else {
                    for (const auto& P : Fn.Params) {
                        if (!bFirst) Teal << ", ";
                        Teal << P.Name << ": " << MapTealType(P.Type);
                        bFirst = false;
                    }
                }
                Teal << "): " << MapTealType(Fn.ReturnStorageType) << "\n";
            }
            for (const auto& Prop : Cls.Properties) {
                Teal << "    " << Prop.Name << ": " << MapTealType(Prop.Type) << "\n";
            }
            Teal << "end\n\n";
            Teal << "return M_" << Cls.Name << "\n";
        }
    }

} // namespace MHeaderTool