#include "LuaBindEmitter.h"
#include "Parsing/ClassParser.h"
#include "Parsing/PropertyParser.h"

#include <fstream>

namespace MHeaderTool {

void LuaBindEmitter::Run(
    const std::filesystem::path& OutDir,
    const std::vector<SParsedClass>& Classes)
{
    std::filesystem::create_directories(OutDir);

    for (const SParsedClass& Cls : Classes)
    {
        // 跳过非 LuaBind 函数(Transport != "LuaBind")
        bool bHasLuaBind = false;
        for (const auto& Fn : Cls.Functions)
        {
            if (Fn.Transport == "LuaBind")
            {
                bHasLuaBind = true;
                break;
            }
        }
        if (!bHasLuaBind) continue;

        std::filesystem::path LuaFile = OutDir / (Cls.Name + ".lua");
        std::filesystem::path TealFile = OutDir / (Cls.Name + ".d.tl");

        // ---- emit .lua ----
        {
            std::ofstream Out(LuaFile);
            Out << "-- Auto-generated by MHeaderTool LuaBindEmitter\n";
            Out << "-- Source class: " << Cls.Name << "\n";
            Out << "local M = require(\"Mession.core\")\n\n";
            Out << "local M_" << Cls.Name << " = {}\n\n";

            for (const auto& Fn : Cls.Functions)
            {
                if (Fn.Transport != "LuaBind") continue;
                Out << "function M_" << Cls.Name << "." << Fn.Name << "(...)\n";
                Out << "    return M.InvokeClass(\"" << Cls.Name << "\", \"" << Fn.Name << "\", {...})\n";
                Out << "end\n\n";
            }

            Out << "M.RegisterClass(\"" << Cls.Name << "\", M_" << Cls.Name << ")\n";
            Out << "return M_" << Cls.Name << "\n";
        }

        // ---- emit .d.tl ----
        {
            std::ofstream Out(TealFile);
            Out << "---@meta mession\n";
            Out << "-- Auto-generated Teal record for " << Cls.Name << "\n";
            Out << "local record " << Cls.Name << "\n";
            for (const auto& Prop : Cls.Properties)
            {
                Out << "    " << Prop.Name << ": " << Prop.Type << "\n";
            }
            Out << "end\n\n";
            Out << "return " << Cls.Name << "\n";
        }
    }
}

} // namespace MHeaderTool