#pragma once

#include "Core/Types.h"
#include "Util/StringUtil.h"
#include "Util/FileUtil.h"
#include <filesystem>
#include <set>

namespace fs = std::filesystem;

namespace MHeaderTool
{

// ============================================================================
// Manifest Generators - 生成 CMake 和其他清单文件
// ============================================================================

class ManifestGenerators
{
public:
    explicit ManifestGenerators(const SOptions& options)
        : Options_(options)
    {
    }

    // 生成 CMake 清单
    std::string GenerateCMakeManifest(
        const std::vector<SParsedClass>& parsedClasses,
        const std::map<std::string, std::vector<std::string>>& typeToHeaders) const
    {
        std::string manifest;
        manifest += "# Auto-generated by MHeaderTool\n";
        manifest += "# Do not edit manually\n\n";
        manifest += "set(MHEADERTOOL_GENERATED_SOURCES\n";

        for (const auto& parsed : parsedClasses)
        {
            fs::path relativePath = parsed.HeaderPath.lexically_relative(Options_.SourceRoot);
            fs::path genPath = relativePath.parent_path() / (parsed.Name + ".gen.cpp");
            manifest += "    ${CMAKE_CURRENT_SOURCE_DIR}/" + genPath.generic_string() + "\n";
        }

        manifest += ")\n\n";

        manifest += "set(MHEADERTOOL_GENERATED_HEADERS\n";

        for (const auto& parsed : parsedClasses)
        {
            fs::path relativePath = parsed.HeaderPath.lexically_relative(Options_.SourceRoot);
            fs::path genPath = relativePath.parent_path() / (parsed.Name + ".gen.h");
            manifest += "    ${CMAKE_CURRENT_SOURCE_DIR}/" + genPath.generic_string() + "\n";
        }

        manifest += ")\n\n";

        return manifest;
    }

    // 生成类型注册表
    std::string GenerateTypeRegistry(
        const std::vector<SParsedClass>& parsedClasses) const
    {
        std::string code;
        code += "#pragma once\n\n";
        code += "// Auto-generated by MHeaderTool\n";
        code += "// Do not edit manually\n\n";
        code += "#include \"Core/Reflection/MTypeRegistry.h\"\n";
        code += "#include <string_view>\n\n";

        code += "namespace MHeaderTool\n";
        code += "{\n\n";

        // Generate type lookup table
        code += "static const STypeDescriptor GTypeDescriptors[] = {\n";

        for (size_t i = 0; i < parsedClasses.size(); ++i)
        {
            const auto& parsed = parsedClasses[i];
            code += "    {\n";
            code += "        \"" + parsed.Name + "\",\n";
            code += "        \"" + parsed.Owner + "\",\n";
            code += "        \"" + std::string(parsed.Kind == EParsedTypeKind::Enum ? "Enum" :
                                             parsed.Kind == EParsedTypeKind::Struct ? "Struct" : "Class") + "\",\n";
            code += "        " + std::to_string(parsed.Properties.size()) + ",\n";
            code += "        " + std::to_string(parsed.Functions.size()) + ",\n";
            code += "    }";

            if (i < parsedClasses.size() - 1)
            {
                code += ",";
            }
            code += "\n";
        }

        code += "};\n\n";

        code += "static constexpr size_t GTypeDescriptorCount = " + std::to_string(parsedClasses.size()) + ";\n\n";

        code += "}  // namespace MHeaderTool\n";

        return code;
    }

    // 生成验证协议 schema
    std::string GenerateValidationSchema(
        const std::vector<SParsedClass>& parsedClasses) const
    {
        std::string json;
        json += "{\n";
        json += "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n";
        json += "  \"title\": \"ValidationProtocol\",\n";
        json += "  \"version\": \"1.0\",\n";
        json += "  \"types\": [\n";

        for (size_t i = 0; i < parsedClasses.size(); ++i)
        {
            const auto& parsed = parsedClasses[i];

            // 只处理有属性的类型
            if (parsed.Properties.empty())
            {
                continue;
            }

            if (i > 0)
            {
                json += ",\n";
            }

            json += "    {\n";
            json += "      \"name\": \"" + parsed.Name + "\",\n";
            json += "      \"owner\": \"" + parsed.Owner + "\",\n";
            json += "      \"fields\": [\n";

            for (size_t j = 0; j < parsed.Properties.size(); ++j)
            {
                const auto& prop = parsed.Properties[j];

                if (j > 0)
                {
                    json += ",\n";
                }

                json += "        {\n";
                json += "          \"name\": \"" + prop.Name + "\",\n";
                json += "          \"type\": \"" + prop.Type + "\",\n";
                json += "          \"kind\": \"" + prop.PropertyKind + "\",\n";

                // 添加元数据
                if (!prop.Metadata.empty())
                {
                    json += "          \"metadata\": {\n";
                    for (size_t k = 0; k < prop.Metadata.size(); ++k)
                    {
                        if (k > 0)
                        {
                            json += ",\n";
                        }
                        json += "            \"" + prop.Metadata[k].Key + "\": \"" + prop.Metadata[k].Value + "\"";
                    }
                    json += "\n          }";
                }
                else
                {
                    // Remove trailing comma if no metadata
                    json += "          \"metadata\": {}";
                }

                json += "\n        }";
            }

            json += "\n      ]\n";
            json += "    }";
        }

        json += "\n  ]\n";
        json += "}\n";

        return json;
    }

    // 生成头文件包含映射
    std::string GenerateHeaderIncludes(
        const std::vector<SParsedClass>& parsedClasses) const
    {
        std::set<std::string> allIncludes;

        for (const auto& parsed : parsedClasses)
        {
            fs::path relativePath = parsed.HeaderPath.lexically_relative(Options_.SourceRoot);
            allIncludes.insert(relativePath.generic_string());
        }

        std::string code;
        code += "#pragma once\n\n";
        code += "// Auto-generated by MHeaderTool\n";
        code += "// Do not edit manually\n\n";

        for (const auto& include : allIncludes)
        {
            code += "#include \"" + include + "\"\n";
        }

        return code;
    }

    // 生成 RPC 消息 ID 映射
    std::string GenerateRpcMessageIds(
        const std::vector<SParsedClass>& parsedClasses) const
    {
        std::string code;
        code += "#pragma once\n\n";
        code += "// Auto-generated by MHeaderTool\n";
        code += "// Do not edit manually\n\n";
        code += "#include <cstdint>\n";
        code += "#include <string_view>\n\n";

        code += "namespace MHeaderTool\n";
        code += "{\n\n";

        code += "enum class EMessageId : uint32_t\n";
        code += "{\n";
        code += "    None = 0,\n";

        uint32_t messageId = 1000;
        for (const auto& parsed : parsedClasses)
        {
            for (const auto& func : parsed.Functions)
            {
                if (func.bIsRpc)
                {
                    code += "    " + parsed.Name + "_" + func.Name + " = " + std::to_string(messageId) + ",\n";
                    ++messageId;
                }
            }
        }

        code += "};\n\n";

        // Generate message name lookup
        code += "static constexpr std::string_view GetMessageName(EMessageId id)\n";
        code += "{\n";
        code += "    switch (id)\n";
        code += "    {\n";

        messageId = 1000;
        for (const auto& parsed : parsedClasses)
        {
            for (const auto& func : parsed.Functions)
            {
                if (func.bIsRpc)
                {
                    code += "        case EMessageId::" + parsed.Name + "_" + func.Name + ": return \"" + func.Name + "\";\n";
                    ++messageId;
                }
            }
        }

        code += "        default: return \"Unknown\";\n";
        code += "    }\n";
        code += "}\n\n";

        code += "}  // namespace MHeaderTool\n";

        return code;
    }

private:
    SOptions Options_;
};

}  // namespace MHeaderTool
