#pragma once

#include "Core/Types.h"
#include "Util/FileUtil.h"
#include "Util/StringUtil.h"
#include <algorithm>
#include <filesystem>
#include <set>

namespace fs = std::filesystem;

namespace MHeaderTool {

    // ============================================================================
    // Manifest Generators - 生成 CMake 和其他清单文件
    // ============================================================================

    class ManifestGenerators {
        public:
        explicit ManifestGenerators(const SOptions& options) : Options_(options) {
        }

        // 将组名标准化为小写
        static MString NormalizeGroupName(const MString& name) {
            MString result;
            for (char c : name) {
                if (c >= 'A' && c <= 'Z') {
                    result += static_cast<char>(c + 32);
                } else if (c != ' ') {
                    result += c;
                }
            }
            return result;
        }

        // 生成 CMake 清单
        MString GenerateCMakeManifest(const TVector<SParsedClass>& parsedClasses, const TMap<MString, TVector<MString>>& typeToHeaders) const {
            (void)typeToHeaders;
            MString manifest;
            manifest += "# Auto-generated by MHeaderTool\n";
            manifest += "# Do not edit manually\n\n";

            // 按 Owner 分组；enum 单独归 MESSION_GENERATED_ENUM_SOURCES
            //（编译进 mession_common——所有链接方都能用反射查 enum）。
            TMap<MString, TVector<MString>> groupSources;
            TVector<MString>                enumSources;
            for (const auto& parsed : parsedClasses) {
                // Skip MHeaderTool source files
                MString headerPath = parsed.HeaderPath.generic_string();
                if (headerPath.find("/Tools/MHeaderTool/") != MString::npos) {
                    continue;
                }

                // 无任何基类的 MCLASS（如独立 demo 类）：非完整反射类——不产出
                // mgenerated.cpp（RegisterAllProperties 等假设类有 MObject 反射基类，
                // ToLegacyClass 会把空 ParentClass 默认成 MObject，故用 AllParentClasses）。
                // 只跳过 class（无基类的演示类）；MSTRUCT（struct——配置/消息等）无基类
                // 但必须保留反射注册（否则 FindStruct 找不到，服务启动失败）。
                // Enum（namespace 级 scoped enum）同样保留——注册单元需要编译。
                if (parsed.AllParentClasses.empty() && parsed.Kind != EParsedTypeKind::Struct && parsed.Kind != EParsedTypeKind::Enum) {
                    continue;
                }

                fs::path genPath      = Options_.OutputDir / (SanitizeIdentifier(parsed.Name) + ".mgenerated.cpp");
                fs::path relativePath = genPath.lexically_relative(Options_.OutputDir);
                MString  source       = "${CMAKE_SOURCE_DIR}/Build/Generated/" + relativePath.generic_string();

                if (parsed.Kind == EParsedTypeKind::Enum) {
                    enumSources.push_back(source);
                    continue;
                }

                // 按 Owner 分组，如果为空则使用 "shared"
                MString group = parsed.Owner.empty() ? "shared" : NormalizeGroupName(parsed.Owner);
                groupSources[group].push_back(source);
            }

            // 输出每个组的源文件
            TVector<MString> allGroups;
            for (const auto& [groupName, sources] : groupSources) {
                allGroups.push_back(groupName);
                MString upperGroup = NormalizeGroupName(groupName);
                std::transform(upperGroup.begin(), upperGroup.end(), upperGroup.begin(), [](unsigned char c) { return std::toupper(c); });
                manifest += "set(MESSION_GENERATED_" + upperGroup + "_SOURCES\n";
                for (const auto& src : sources) {
                    manifest += "    " + src + "\n";
                }
                manifest += ")\n\n";
            }

            // 设置组列表
            manifest += "set(MESSION_GENERATED_GROUPS";
            for (const auto& group : allGroups) {
                manifest += " " + group;
            }
            manifest += ")\n";

            // namespace enum 注册单元——编进 mession_common(见 CMakeLists)
            manifest += "set(MESSION_GENERATED_ENUM_SOURCES\n";
            for (const auto& src : enumSources) {
                manifest += "    " + src + "\n";
            }
            manifest += ")\n";

            return manifest;
        }

        // 生成类型注册表
        MString GenerateTypeRegistry(const TVector<SParsedClass>& parsedClasses) const {
            MString code;
            code += "#pragma once\n\n";
            code += "// Auto-generated by MHeaderTool\n";
            code += "// Do not edit manually\n\n";
            code += "#include \"Core/Reflection/MTypeRegistry.h\"\n";
            code += "#include <string_view>\n\n";

            code += "namespace MHeaderTool\n";
            code += "{\n\n";

            // Generate type lookup table
            code += "static const STypeDescriptor GTypeDescriptors[] = {\n";

            for (size_t i = 0; i < parsedClasses.size(); ++i) {
                const auto& parsed = parsedClasses[i];
                code += "    {\n";
                code += "        \"" + parsed.Name + "\",\n";
                code += "        \"" + parsed.Owner + "\",\n";
                code += "        \"" + MString(parsed.Kind == EParsedTypeKind::Enum ? "Enum" : parsed.Kind == EParsedTypeKind::Struct ? "Struct" : "Class") + "\",\n";
                code += "        " + std::to_string(parsed.Properties.size()) + ",\n";
                code += "        " + std::to_string(parsed.Functions.size()) + ",\n";
                code += "    }";

                if (i < parsedClasses.size() - 1) {
                    code += ",";
                }
                code += "\n";
            }

            code += "};\n\n";

            code += "static constexpr size_t GTypeDescriptorCount = " + std::to_string(parsedClasses.size()) + ";\n\n";

            code += "}  // namespace MHeaderTool\n";

            return code;
        }

        // 生成验证协议 schema
        MString GenerateValidationSchema(const TVector<SParsedClass>& parsedClasses) const {
            MString json;
            json += "{\n";
            json += "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n";
            json += "  \"title\": \"ValidationProtocol\",\n";
            json += "  \"version\": \"1.0\",\n";
            json += "  \"types\": [\n";

            for (size_t i = 0; i < parsedClasses.size(); ++i) {
                const auto& parsed = parsedClasses[i];

                // 只处理有属性的类型
                if (parsed.Properties.empty()) {
                    continue;
                }

                if (i > 0) {
                    json += ",\n";
                }

                json += "    {\n";
                json += "      \"name\": \"" + parsed.Name + "\",\n";
                json += "      \"owner\": \"" + parsed.Owner + "\",\n";
                json += "      \"fields\": [\n";

                for (size_t j = 0; j < parsed.Properties.size(); ++j) {
                    const auto& prop = parsed.Properties[j];

                    if (j > 0) {
                        json += ",\n";
                    }

                    json += "        {\n";
                    json += "          \"name\": \"" + prop.Name + "\",\n";
                    json += "          \"type\": \"" + prop.Type + "\",\n";
                    json += "          \"kind\": \"" + prop.PropertyKind + "\",\n";

                    // 添加元数据
                    if (!prop.Metadata.empty()) {
                        json += "          \"metadata\": {\n";
                        for (size_t k = 0; k < prop.Metadata.size(); ++k) {
                            if (k > 0) {
                                json += ",\n";
                            }
                            json += "            \"" + prop.Metadata[k].Key + "\": \"" + prop.Metadata[k].Value + "\"";
                        }
                        json += "\n          }";
                    } else {
                        // Remove trailing comma if no metadata
                        json += "          \"metadata\": {}";
                    }

                    json += "\n        }";
                }

                json += "\n      ]\n";
                json += "    }";
            }

            json += "\n  ]\n";
            json += "}\n";

            return json;
        }

        // 生成头文件包含映射
        MString GenerateHeaderIncludes(const TVector<SParsedClass>& parsedClasses) const {
            TSet<MString> allIncludes;

            for (const auto& parsed : parsedClasses) {
                fs::path relativePath = parsed.HeaderPath.lexically_relative(Options_.SourceRoot);
                allIncludes.insert(relativePath.generic_string());
            }

            MString code;
            code += "#pragma once\n\n";
            code += "// Auto-generated by MHeaderTool\n";
            code += "// Do not edit manually\n\n";

            for (const auto& include : allIncludes) {
                code += "#include \"" + include + "\"\n";
            }

            return code;
        }

        // 生成 RPC 消息 ID 映射
        MString GenerateRpcMessageIds(const TVector<SParsedClass>& parsedClasses) const {
            MString code;
            code += "#pragma once\n\n";
            code += "// Auto-generated by MHeaderTool\n";
            code += "// Do not edit manually\n\n";
            code += "#include <cstdint>\n";
            code += "#include <string_view>\n\n";

            code += "namespace MHeaderTool\n";
            code += "{\n\n";

            code += "enum class EMessageId : uint32_t\n";
            code += "{\n";
            code += "    None = 0,\n";

            uint32_t messageId = 1000;
            for (const auto& parsed : parsedClasses) {
                for (const auto& func : parsed.Functions) {
                    if (func.bIsRpc) {
                        code += "    " + parsed.Name + "_" + func.Name + " = " + std::to_string(messageId) + ",\n";
                        ++messageId;
                    }
                }
            }

            code += "};\n\n";

            // Generate message name lookup
            code += "static constexpr std::string_view GetMessageName(EMessageId id)\n";
            code += "{\n";
            code += "    switch (id)\n";
            code += "    {\n";

            messageId = 1000;
            for (const auto& parsed : parsedClasses) {
                for (const auto& func : parsed.Functions) {
                    if (func.bIsRpc) {
                        code += "        case EMessageId::" + parsed.Name + "_" + func.Name + ": return \"" + func.Name + "\";\n";
                        ++messageId;
                    }
                }
            }

            code += "        default: return \"Unknown\";\n";
            code += "    }\n";
            code += "}\n\n";

            code += "}  // namespace MHeaderTool\n";

            return code;
        }

        // 生成 MClientManifest — 客户端调用清单（FunctionId → OwnerType/FunctionName/Response/Target）
        //
        // 扫描所有 Transport == "Client" 或 Transport == "ClientCall" 的 MFUNCTION，
        // 用与 C++ 端 ComputeStableClientFunctionId / ComputeStableReflectId 一致的 FNV-1a 算法
        // 算出 FunctionId。Python 侧会读取这个 .cpp 里的 GClientManifestEntries 表。
        //
        // 注意：生成器收集"客户端可经 Gateway 调用的 ServerCall"（如 MEchoService.Echo /
        // EchoAwait / TriggerNotify / RegisterDynamicActor），表非空；Gateway 经
        // FindByFunctionId 路由。MFUNCTION(CallClient) 走 GenerateClientDownlinkManifest
        //（下行方向，单独的表 + 服务端调用 stub）。
        MString GenerateClientManifest(const TVector<SParsedClass>& parsedClasses) const {
            MString code;
            code += "// Auto-generated by MHeaderTool — DO NOT EDIT\n";
            code += "// Source: scanned 客户端可经 Gateway 调用的函数（ServerCall;MFUNCTION(CallClient) 走下行 manifest）entries\n\n";
            code += "#include \"Common/Net/Rpc/MClientManifest.generated.h\"\n\n";

            // First pass: collect entries with stable FunctionId matching C++ side.
            // Emitted entries have to be valid C++ struct initializer lists;
            // we keep them as raw string parts rather than std::tuple to avoid lifetime surprises.
            TVector<MString> entryLines;

            for (const auto& parsed : parsedClasses) {
                // 跳过 MHeaderTool 自己的源码
                MString headerPath = parsed.HeaderPath.generic_string();
                if (headerPath.find("/Tools/MHeaderTool/") != MString::npos) {
                    continue;
                }

                for (const auto& func : parsed.Functions) {
                    // 客户端经 Gateway 可调用的函数：Client / ClientCall / ServerCall
                    //（ServerCall 是客户端→服务器方向——客户端发 FunctionId 经 Gateway
                    //  路由到服务端；manifest 提供 FindByFunctionId 查表）。
                    const bool bIsClient = func.Transport == "Client" || func.Transport == "ClientCall" || func.Transport == "ServerCall";
                    if (!bIsClient) {
                        continue;
                    }

                    // 优先用 ClientApi name 算 id（与 Class.h:50-53 的 ComputeStableClientFunctionId 一致）
                    // 否则回退到 (ClassName, FunctionName) 这条稳定 id 路径
                    MString scopeName;
                    MString memberName;
                    if (!func.ClientApi.empty()) {
                        scopeName  = "MClientApi";
                        memberName = func.ClientApi;
                    } else {
                        scopeName  = parsed.Name;
                        memberName = func.Name;
                    }

                    const uint16_t functionId = ComputeStableReflectIdCpp(scopeName, memberName);

                    // Response type = 第一个返回值参数的类型
                    MString responseType = "void";
                    if (!func.ReturnType.empty()) {
                        responseType = func.ReturnType;
                    }

                    entryLines.push_back("    { " + std::to_string(functionId) + ", \"" + EscapeCppStringLiteral(parsed.Name) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(func.Name) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(responseType) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(func.Target) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(func.ClientApi) +
                                         "\""
                                         " }");
                }
            }

            code += "const MClientManifest::SEntry MClientManifest::GClientManifestEntries[] = {\n";
            for (size_t i = 0; i < entryLines.size(); ++i) {
                code += entryLines[i];
                if (i + 1 < entryLines.size()) {
                    code += ",";
                }
                code += "\n";
            }
            code += "};\n";
            code += "const size_t MClientManifest::GClientManifestEntryCount = " + std::to_string(entryLines.size()) + ";\n";
            code += "const MClientManifest::SEntry* MClientManifest::FindByFunctionId(uint16_t FunctionId) {\n";
            code += "    if (FunctionId == 0) return nullptr;\n";
            code += "    for (size_t i = 0; i < GClientManifestEntryCount; ++i) {\n";
            code += "        if (GClientManifestEntries[i].FunctionId == FunctionId) {\n";
            code += "            return &GClientManifestEntries[i];\n";
            code += "        }\n";
            code += "    }\n";
            code += "    return nullptr;\n";
            code += "}\n";

            return code;
        }

        // 下行 FunctionId 常量头：业务侧 include 后直接用 MDownlink_<Class>_<Func>。
        MString GenerateClientDownlinkHeader(const TVector<SParsedClass>& parsedClasses) const {
            MString code;
            code += "#pragma once\n";
            code += "// Auto-generated by MHeaderTool — DO NOT EDIT\n";
            code += "// Source: scanned MFUNCTION(CallClient) entries (下行 FunctionId 常量 + 服务端调用 stub)\n\n";
            code += "#include <cstdint>\n";
            code += "#include \"Common/Net/ServiceDiscovery/EndpointCache.h\"\n";
            code += "#include \"Common/Net/Rpc/RpcPayload.h\"\n";
            code += "#include \"Common/Net/Rpc/RpcServerCall.h\"\n";
            code += "#include \"Protocol/Messages/Common/ClientDownlinkMessages.h\"\n\n";
            for (const auto& parsed : parsedClasses) {
                MString headerPath = parsed.HeaderPath.generic_string();
                if (headerPath.find("/Tools/MHeaderTool/") != MString::npos) {
                    continue;
                }
                for (const auto& func : parsed.Functions) {
                    if (func.Transport != "CallClient") {
                        continue;
                    }
                    MString scopeName;
                    MString memberName;
                    if (!func.ClientApi.empty()) {
                        scopeName  = "MClientApi";
                        memberName = func.ClientApi;
                    } else {
                        scopeName  = parsed.Name;
                        memberName = func.Name;
                    }
                    const uint16_t functionId = ComputeStableReflectIdCpp(scopeName, memberName);
                    code += "// 下行通知 " + parsed.Name + "::" + func.Name + "\n";
                    code += "inline constexpr uint16_t MDownlink_" + parsed.Name + "_" + func.Name + " = " + std::to_string(functionId) + ";\n";

                    // 服务端调用 stub（单参数消息约定,PoC）：业务侧
                    // MDownlinkCall_<Class>_<Func>(connId, msg) 即把下行消息经
                    // Gateway PushClientDownlink 推给客户端（connId==0 广播）。
                    // 与 EchoService::TriggerNotify 的手写样板等价,由生成器统一产出。
                    if (func.Params.size() == 1) {
                        const MString ParamType = func.Params[0].Type;
                        code += "inline SFutureResult<SEmptyServerMessage> MDownlinkCall_" + parsed.Name + "_" + func.Name +
                                "(uint64 GatewayConnectionId, " + ParamType + " Msg) {\n";
                        code += "    FClientDownlinkPushRequest Req;\n";
                        code += "    Req.GatewayConnectionId = GatewayConnectionId;\n";
                        code += "    Req.FunctionId          = MDownlink_" + parsed.Name + "_" + func.Name + ";\n";
                        code += "    Req.Payload             = BuildPayload(Msg);\n";
                        code += "    TSharedPtr<MServerConnection> GatewayConn = MEndpointCache::Get().GetOrConnect(EServerType::Gateway);\n";
                        code += "    if (!GatewayConn) {\n";
                        code += "        return MakeRpcErrorFuture<SEmptyServerMessage>(\"gateway_unavailable\", \"MDownlinkCall_" + parsed.Name + "_" + func.Name + "\");\n";
                        code += "    }\n";
                        code += "    return CallServerFunction<SEmptyServerMessage>(GatewayConn, EServerType::Gateway, \"PushClientDownlink\", Req);\n";
                        code += "}\n";
                    }
                }
            }
            return code;
        }

        // 服务端→客户端下行通知清单：收集所有 MFUNCTION(CallClient) 声明，
        // 为每个分配下行 FunctionId（ClientApi 或 (OwnerType, FunctionName) 稳定 id），
        // emit 到 MClientDownlinkManifest.mgenerated.cpp（FindByFunctionId 查表）。
        MString GenerateClientDownlinkManifest(const TVector<SParsedClass>& parsedClasses) const {
            MString code;
            code += "// Auto-generated by MHeaderTool — DO NOT EDIT\n";
            code += "// Source: scanned MFUNCTION(CallClient) entries (服务端→客户端下行通知)\n\n";
            code += "#include \"Common/Net/Rpc/MClientDownlinkManifest.h\"\n\n";

            TVector<MString> entryLines;
            for (const auto& parsed : parsedClasses) {
                MString headerPath = parsed.HeaderPath.generic_string();
                if (headerPath.find("/Tools/MHeaderTool/") != MString::npos) {
                    continue;
                }
                for (const auto& func : parsed.Functions) {
                    if (func.Transport != "CallClient") {
                        continue;
                    }
                    // 与上行 manifest 同规则：优先 ClientApi name 算 id（MClientApi 域），
                    // 否则回退 (ClassName, FunctionName)。
                    MString scopeName;
                    MString memberName;
                    if (!func.ClientApi.empty()) {
                        scopeName  = "MClientApi";
                        memberName = func.ClientApi;
                    } else {
                        scopeName  = parsed.Name;
                        memberName = func.Name;
                    }
                    const uint16_t functionId = ComputeStableReflectIdCpp(scopeName, memberName);

                    MString responseType = "void";
                    if (!func.ReturnType.empty()) {
                        responseType = func.ReturnType;
                    }
                    entryLines.push_back("    { " + std::to_string(functionId) + ", \"" + EscapeCppStringLiteral(parsed.Name) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(func.Name) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(responseType) +
                                         "\""
                                         " }");
                }
            }

            code += "const MClientDownlinkManifest::SDownlinkEntry MClientDownlinkManifest::GDownlinkEntries[] = {\n";
            for (size_t i = 0; i < entryLines.size(); ++i) {
                code += entryLines[i];
                if (i + 1 < entryLines.size()) {
                    code += ",";
                }
                code += "\n";
            }
            code += "};\n";
            code += "const size_t MClientDownlinkManifest::GDownlinkEntryCount = " + std::to_string(entryLines.size()) + ";\n";
            code += "const MClientDownlinkManifest::SDownlinkEntry* MClientDownlinkManifest::FindByFunctionId(uint16_t FunctionId) {\n";
            code += "    if (FunctionId == 0) return nullptr;\n";
            code += "    for (size_t i = 0; i < GDownlinkEntryCount; ++i) {\n";
            code += "        if (GDownlinkEntries[i].FunctionId == FunctionId) {\n";
            code += "            return &GDownlinkEntries[i];\n";
            code += "        }\n";
            code += "    }\n";
            code += "    return nullptr;\n";
            code += "}\n";

            return code;
        }

        // F0 actor-member-framework §3.2:生成成员 RPC 注册表
        // (GMemberRpcEntries + 查找函数)。扫描 Type=ActorMember 类的
        // MFUNCTION(ServerCall),FunctionId 用 ComputeStableReflectIdCpp
        // (member 类名, 方法名)——与 ServerCall 的 (类, 方法) 域一致,
        // 不同 member 类同名方法不撞。框架分发器
        // (DispatchFrameworkMemberCall, Common/Runtime/Actor/ActorMember.cpp)
        // 按 FunctionId 查表 → 请求取 PlayerId → 宿主成员表 → 反射调用。
        MString GenerateMemberRpcManifest(const TVector<SParsedClass>& parsedClasses) const {
            MString code;
            code += "// Auto-generated by MHeaderTool — DO NOT EDIT\n";
            code += "// Source: scanned Type=ActorMember MFUNCTION(ServerCall) entries\n\n";
            code += "#include \"Common/Runtime/Actor/MemberRpcManifest.generated.h\"\n\n";

            TVector<MString> entryLines;
            for (const auto& parsed : parsedClasses) {
                MString headerPath = parsed.HeaderPath.generic_string();
                if (headerPath.find("/Tools/MHeaderTool/") != MString::npos) {
                    continue;
                }
                if (parsed.Kind != EParsedTypeKind::Class || parsed.ReflectionType != "ActorMember") {
                    continue;
                }
                for (const auto& func : parsed.Functions) {
                    if (func.Transport != "ServerCall") {
                        continue;
                    }
                    const uint16_t functionId = ComputeStableReflectIdCpp(parsed.Name, func.Name);
                    const MString  requestType = func.Params.empty() ? "" : func.Params[0].StorageType;
                    entryLines.push_back("    { " + std::to_string(functionId) +
                                         ", \"" + EscapeCppStringLiteral(parsed.Name) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(func.Name) +
                                         "\""
                                         ", \"" +
                                         EscapeCppStringLiteral(requestType) +
                                         "\" }");
                }
            }

            code += "const SMemberRpcEntry GMemberRpcEntries[] = {\n";
            for (size_t i = 0; i < entryLines.size(); ++i) {
                code += entryLines[i];
                if (i + 1 < entryLines.size()) {
                    code += ",";
                }
                code += "\n";
            }
            code += "};\n";
            code += "const size_t GMemberRpcEntryCount = " + std::to_string(entryLines.size()) + ";\n";
            code += "\n";
            code += "const SMemberRpcEntry* FindMemberRpcEntryByFunctionId(uint16_t FunctionId) {\n";
            code += "    if (FunctionId == 0) return nullptr;\n";
            code += "    for (size_t i = 0; i < GMemberRpcEntryCount; ++i) {\n";
            code += "        if (GMemberRpcEntries[i].FunctionId == FunctionId) {\n";
            code += "            return &GMemberRpcEntries[i];\n";
            code += "        }\n";
            code += "    }\n";
            code += "    return nullptr;\n";
            code += "}\n";
            code += "\n";
            code += "const SMemberRpcEntry* FindMemberRpcEntry(size_t Index) {\n";
            code += "    if (Index >= GMemberRpcEntryCount) return nullptr;\n";
            code += "    return &GMemberRpcEntries[Index];\n";
            code += "}\n";
            code += "\n";
            code += "size_t GetMemberRpcEntryCount() {\n";
            code += "    return GMemberRpcEntryCount;\n";
            code += "}\n";

            return code;
        }

        private:
        // 与 Common/Runtime/Reflect/Class.h 的 ComputeStableReflectId / ComputeStableClientFunctionId
        // 完全一致：FNV-1a 32-bit，然后高 16 XOR 低 16，0 → 1
        static uint16_t ComputeStableReflectIdCpp(const MString& ScopeName, const MString& MemberName) {
            constexpr uint32_t OffsetBasis = 2166136261u;
            constexpr uint32_t Prime       = 16777619u;
            const MString      Separator   = "::";

            uint32_t Hash    = OffsetBasis;
            auto     MixInto = [&Hash, &Prime](const MString& Text) {
                for (char ch : Text) {
                    Hash ^= static_cast<uint8_t>(ch);
                    Hash *= Prime;
                }
            };

            MixInto(ScopeName);
            MixInto(Separator);
            MixInto(MemberName);

            const uint16_t Folded = static_cast<uint16_t>((Hash >> 16) ^ (Hash & 0xFFFFu));
            return Folded == 0 ? 1u : Folded;
        }

        SOptions Options_;
    };

} // namespace MHeaderTool
