add_library(mession_lua STATIC
    LuaScriptState.cpp
    LuaTypeBridge.cpp
    LuaCoroutineBridge.cpp
    LuaModule.cpp
    LuaRepl.cpp
    LuaEngine.cpp
    LuaHotReload.cpp
    MobDebugServer.cpp
    MLuaVector.cpp
    MLuaMap.cpp
    MLuaLog.cpp
    MLuaFormat.cpp
    MLuaRpc.cpp
    FPendingCall.cpp
)
target_include_directories(mession_lua
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
)
target_link_libraries(mession_lua
    PUBLIC
        mession_lua_vendor
        mession_common
        mession_netdriver
        mession_script_abstract
        fmt::fmt-header-only
)
configure_mession_compile_options(mession_lua)