#include "Common/Runtime/Log/Tests/TestHarness.h"
#include "Common/Runtime/Async/AsyncContext.h"
#include "Common/Runtime/Async/MAsync.h"
#include "Common/Runtime/Async/AwaitMacros.h"
#include "Common/Runtime/EventLoop/TaskEventLoop.h"
#include "Common/Runtime/Concurrency/Promise.h"
#include "MEchoService_AsyncFrames.h"
#include "Protocol/Messages/EchoService/FSampleEchoMessages.h"
#include "Servers/App/ServerCallAsyncSupport.h"

#include <utility>

namespace
{
SFutureResult<FSampleEchoResponse> MakeReadyOk(const MString& EchoText)
{
    FSampleEchoResponse R;
    R.Echo = EchoText;
    R.SourceActorId = 0xCAFE;
    R.SourceServerName = "MockService";
    MPromise<TResult<FSampleEchoResponse, FAppError>> P;
    auto F = P.GetFuture();
    P.SetValue(TResult<FSampleEchoResponse, FAppError>::Ok(std::move(R)));
    return SFutureResult<FSampleEchoResponse>(std::move(F));
}
}

// P3 v1 inline-body design: the Frame struct is now auto-generated by
// MHeaderTool from `MFUNCTION(ServerCall, Async)`. v1 has NO state machine
// — `AwaitOk` is a pass-through that returns Awaited verbatim, snapshots
// the awaited future into AwaitedSlot, and records the Ok value into
// StoredValue. P4 will replace this with the real state machine.
//
// These tests exercise:
//   - AwaitOk returns the awaited future so `return AWAIT_OK(expr);` matches
//     SFutureResult<Resp> return type.
//   - Ready-Ok path: AwaitedSlot is set, StoredValue snapshot matches.
//   - AWAIT_OK macro expands to Frame->AwaitOk(expr) — verified by passing
//     a movable expression through it (the local `Frame` symbol must exist).

TEST_CASE(AsyncFrame_AwaitOk_ReadyOk_StoresValue)
{
    auto Frame = MakeShared<MHeaderTool_AsyncFrame_MEchoService_EchoAwait>();
    EXPECT_TRUE(!Frame->AwaitedSlot.IsReady());
    EXPECT_TRUE(Frame->StoredValue.Echo == "");

    SFutureResult<FSampleEchoResponse> Returned = AWAIT_OK(MakeReadyOk("ready-ok"));

    EXPECT_TRUE(Returned.IsReady());
    EXPECT_TRUE(Frame->AwaitedSlot.IsReady());
    EXPECT_TRUE(Frame->StoredValue.Echo == "ready-ok");
    EXPECT_TRUE(Frame->StoredValue.SourceServerName == "MockService");
    EXPECT_TRUE(Frame->StoredValue.SourceActorId == 0xCAFE);

    // AwaitOk is pass-through: AwaitedSlot and Returned share the same
    // underlying TResult state. PeekResult() is non-destructive — repeated
    // inspection is safe; GetResult() would move out the value.
    auto R = Returned.PeekResult();
    EXPECT_TRUE(R.IsOk());
    EXPECT_TRUE(R.GetValue().Echo == "ready-ok");
}

TEST_CASE(AsyncFrame_AwaitOk_AwaitedSlotAndReturnedAreSameFuture)
{
    auto Frame = MakeShared<MHeaderTool_AsyncFrame_MEchoService_EchoAwait>();

    auto Ready = MakeReadyOk("same-future");
    SFutureResult<FSampleEchoResponse> Returned = AWAIT_OK(std::move(Ready));

    // Both should be ready and report the same value.
    EXPECT_TRUE(Frame->AwaitedSlot.IsReady());
    EXPECT_TRUE(Returned.IsReady());
    EXPECT_TRUE(Frame->AwaitedSlot.PeekResult().GetValue().Echo ==
                Returned.PeekResult().GetValue().Echo);
}

TEST_CASE(AsyncFrame_AwaitOk_PendingRecordsInAwaitedSlot)
{
    auto Frame = MakeShared<MHeaderTool_AsyncFrame_MEchoService_EchoAwait>();
    EXPECT_TRUE(!Frame->AwaitedSlot.IsReady());

    MPromise<TResult<FSampleEchoResponse, FAppError>> P;
    auto Pending = SFutureResult<FSampleEchoResponse>(P.GetFuture());
    EXPECT_TRUE(!Pending.IsReady());

    SFutureResult<FSampleEchoResponse> Returned = AWAIT_OK(std::move(Pending));

    // AwaitedSlot captures the pending future; Returned is the same handle.
    EXPECT_TRUE(!Frame->AwaitedSlot.IsReady());
    EXPECT_TRUE(!Returned.IsReady());

    // Resolve the promise externally — both AwaitedSlot and Returned
    // transition to ready (they share the underlying future state).
    FSampleEchoResponse R;
    R.Echo = "resolved";
    R.SourceActorId = 0xBEEF;
    R.SourceServerName = "MockPending";
    P.SetValue(TResult<FSampleEchoResponse, FAppError>::Ok(std::move(R)));

    EXPECT_TRUE(Frame->AwaitedSlot.IsReady());
    EXPECT_TRUE(Returned.IsReady());
    EXPECT_TRUE(Frame->AwaitedSlot.PeekResult().GetValue().Echo == "resolved");
    EXPECT_TRUE(Returned.PeekResult().GetValue().Echo == "resolved");
}

int main()
{
    std::printf("Running AsyncFrameTest (P3: MHeaderTool-generated AsyncFrame)\n");

    std::printf("[ AsyncFrame_AwaitOk_ReadyOk_StoresValue ]\n");
    Test_AsyncFrame_AwaitOk_ReadyOk_StoresValue();

    std::printf("[ AsyncFrame_AwaitOk_AwaitedSlotAndReturnedAreSameFuture ]\n");
    Test_AsyncFrame_AwaitOk_AwaitedSlotAndReturnedAreSameFuture();

    std::printf("[ AsyncFrame_AwaitOk_PendingRecordsInAwaitedSlot ]\n");
    Test_AsyncFrame_AwaitOk_PendingRecordsInAwaitedSlot();

    RUN_TESTS();
}