add_executable(LuaTypeBridgeTest
    TestLuaTypeBridge.cpp
)
add_executable(LuaCoroutineTest
    TestLuaCoroutine.cpp
)
add_executable(LuaInstanceHandleTest
    TestLuaInstanceHandle.cpp
)
add_executable(LuaVectorTest
    TestLuaVector.cpp
)
add_executable(LuaMapTest
    TestLuaMap.cpp
)
add_executable(LuaLogTest
    TestLuaLog.cpp
)
add_executable(LuaFormatTest
    TestLuaFormat.cpp
)
add_executable(LuaRpcTest
    TestLuaRpc.cpp
)
add_executable(LuaHotReloadTest
    TestLuaHotReload.cpp
)

target_include_directories(LuaTypeBridgeTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaCoroutineTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaInstanceHandleTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaVectorTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaMapTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaLogTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaFormatTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaRpcTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)
target_include_directories(LuaHotReloadTest
    PRIVATE
        ${CMAKE_SOURCE_DIR}/Source
        ${CMAKE_SOURCE_DIR}/Source/ThirdParty/lua/src
        ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(LuaTypeBridgeTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
)
target_link_libraries(LuaCoroutineTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
)
target_link_libraries(LuaInstanceHandleTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
        mession_script_abstract
)
target_link_libraries(LuaVectorTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
)
target_link_libraries(LuaMapTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
)
target_link_libraries(LuaLogTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
)
target_link_libraries(LuaFormatTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
        fmt::fmt-header-only
)
target_link_libraries(LuaRpcTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
)
target_link_libraries(LuaHotReloadTest
    PRIVATE
        mession_lua
        mession_lua_vendor
        mession_common
        mession_script_abstract
)

configure_mession_compile_options(LuaTypeBridgeTest)
configure_mession_compile_options(LuaCoroutineTest)
configure_mession_compile_options(LuaInstanceHandleTest)
configure_mession_compile_options(LuaVectorTest)
configure_mession_compile_options(LuaMapTest)
configure_mession_compile_options(LuaLogTest)
configure_mession_compile_options(LuaFormatTest)
configure_mession_compile_options(LuaRpcTest)
configure_mession_compile_options(LuaHotReloadTest)