# Mession Mgo Server Config
# Override with env:
#   MESSION_MGO_PORT
#   MESSION_ROUTER_ADDR
#   MESSION_ROUTER_PORT
#   MESSION_MGO_DEBUG_HTTP_PORT
#   MESSION_MGO_MONGO_ENABLE
#   MESSION_MGO_MONGO_URI
#   MESSION_MGO_MONGO_DB
#   MESSION_MGO_MONGO_COLLECTION
#   MESSION_MGO_DB_WORKERS

port=8006
router_addr=127.0.0.1
router_port=8005
server_name=Mgo01
zone_id=0
debug_http_port=0

mongo_enable=0
mongo_uri=mongodb://127.0.0.1:27017
mongo_db=mession
mongo_collection=world_snapshots
mongo_db_workers=1
