# Mession World Server Config
# Override with env: MESSION_WORLD_PORT, MESSION_ROUTER_ADDR, MESSION_ROUTER_PORT, MESSION_LOGIN_ADDR, MESSION_LOGIN_PORT, MESSION_ZONE_ID, MESSION_WORLD_DEBUG_HTTP_PORT, MESSION_WORLD_MGO_PERSISTENCE_ENABLE, MESSION_WORLD_OWNER_SERVER_ID

port=8003
router_addr=127.0.0.1
router_port=8005
login_addr=127.0.0.1
login_port=8002
zone_id=0
owner_server_id=3
